### ISSUE TITLE
Klipper support

### ISSUE THREAD

**Issue by rainerschulte** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1905] opened 2021-05-08 07:37 UTC
I currently build a VORON Legacy which will replace my old ANET PK8. 
I want to reuse all technical components for this Project. I have an SKR 1.4 Turbo and the TFT 35 V2.
The SKR is flashed to KLIPPER and the Display cannot talk to the Board. So it seems to require a different Firmware to connect the Display with SKR 1.4 Turbo using KLIPPER. 

Is there something planned in this direction, because KLIPPER seems win popularity in 3D Printing?

**Comment by bigtreetech** [comment] 2021-05-08 08:09
Hello, this is because klipper doesn't support external Serial(UART) host at present, so all Serial screens can't work with klipper at present.
TFT35 V3.0 and other TFT hardware with 12864 mode (EXP-1 EXP-2) can work in 12864 mode with klipper. (But at present, the firmware of this project has some compatibility problems with klipper, which will cause characters to be covered. This problem will be resolved in the last two weeks)

**Comment by oldman4U** [comment] 2021-05-08 08:15
And please see #290 and feature request ticket.

**Comment by oldman4U** [comment] 2021-05-08 20:43
And I forgot #1555. Your ticket is a duplicate of two other tickets.

Please help the community and close the ticket once you do not need it anymore. Thank you

**Comment by oldman4U** [comment] 2021-05-10 09:22
@rainerschulte 

Are you watching your own ticket?

**Comment by rainerschulte** [comment] 2021-05-11 19:25
Hi,

 

I watched the other tickets too.
 

-- 
Der Wahnsinn hat einen Namen!

Rainer (Wahnsinn) Schulte

 
 

Gesendet: Montag, 10. Mai 2021 um 11:22 Uhr
Von: "oldman4U" ***@***.***>
An: "bigtreetech/BIGTREETECH-TouchScreenFirmware" ***@***.***>
Cc: "rainerschulte" ***@***.***>, "Mention" ***@***.***>
Betreff: Re: [bigtreetech/BIGTREETECH-TouchScreenFirmware] Klipper support (#1905)


 

@rainerschulte

Are you watching your own ticket?

**Comment by oldman4U** [comment] 2021-05-14 06:47
@Msq001

Starting with #290, there are several tickets related to Klipper support, it is in the ToDo and Feature Request List and there is a PR for it also. This particular ticket does not add any additional information.

Please check and close this ticket. Thank you

**Closed** 2021-05-14 18:39 UTC
Labels: enhancement
