### ISSUE TITLE
[BUG] Installing pre-configured firmware give errors/warnings

### ISSUE THREAD

**Issue by ralfiii** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1225] opened 2020-11-01 21:12 UTC
### Description

When I update my TFT35 display with the prepared firmware from the folder "Copy to SD Card root directory to update - Unified Menu Material theme" I get errors
* S_load.bmp and one other bitmap is missing.
* during "updating configuration" I get "Invalid keyword: mesh_max_color:2

Also strange: Is it normal that the GUI doesn't show bed and extruder temperature when heating up for a print job? My display stays as in the screenshot until the print starts, only then the current and expected temperatures are shown.

### Steps to reproduce

I downloaded the zip from github, copied
* TFT35 (folder)
* BIGTREE_TFT35_V3.0_E3.26.x.bin
* config.ini
on an SD card and inserted the card into the display to update.

### Hardware Variant

It's this display:
https://www.amazon.de/dp/B089SPPGKJ/?coliid=I3A06Y8U7J9O7E&colid=1Y5TQLAWV23RQ&psc=1&ref_=lv_ov_lig_dp_it

### TFT Firmware Version & Main Board Firmware details
* Marlin 2.0.7.2
* TFT_E3_V3.0.26.x Sept 12 2020

### Additional Information

![IMG_20201030_235628](https://user-images.githubusercontent.com/11887064/97815249-01bc0d80-1c8d-11eb-9308-07d56502898a.jpg)
![IMG_20201030_235658](https://user-images.githubusercontent.com/11887064/97815252-02ed3a80-1c8d-11eb-9704-99e7da9f3cb7.jpg)
![IMG_20201030_235818](https://user-images.githubusercontent.com/11887064/97815253-041e6780-1c8d-11eb-8799-32e7461e8620.jpg)
![IMG_20201030_235855](https://user-images.githubusercontent.com/11887064/97815255-04b6fe00-1c8d-11eb-8a29-f7ef75b67bbb.jpg)
![IMG_20201030_235943](https://user-images.githubusercontent.com/11887064/97815256-054f9480-1c8d-11eb-910e-1b27d49d3cf8.jpg)

**Comment by radek8** [comment] 2020-11-01 22:59
The problem is in the old version of the precompiled file and the new ini file and and icons.
I will compile my own bin file, if you can't, I'll send you new versions for your display.

**Comment by radek8** [comment] 2020-11-01 23:01
[BIGTREE_TFT35_V3.0.26.x.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/5471930/BIGTREE_TFT35_V3.0.26.x.zip)

**Comment by radek8** [comment] 2020-11-01 23:17
The temperature update problem you describe is standard behavior when printing from an SD card integrated on the Marlin board.
If you print from the SD card on the TFT display, the temperature is updated already during heating.

**Comment by oldman4U** [comment] 2020-11-02 03:15
@radek8 The temp updates with the new firmware also when printing from on board sd card.

**Comment by radek8** [comment] 2020-11-02 06:55
> @radek8 The temp updates with the new firmware also when printing from on board sd card.
> 
> Using Marlin 2.0.7.2.
> 
> Do you know who is responsible for the pre compiled versions?

For me, printing from SD to SKR behaves the same as described.
If you behave differently, it could be due to some choice in the Marlin or TFT configuration.

**Comment by oldman4U** [comment] 2020-11-02 07:53
> 
> For me, printing from SD to SKR behaves the same as described.
> 
> If you behave differently, it could be due to some choice in the Marlin or TFT configuration.

Using pre compiled firmware or in general?

Do you know who is responsible for the pre compiled firmware?

**Comment by radek8** [comment] 2020-11-02 08:10
I compile FW for TFT and SKR myself.

**Comment by radek8** [comment] 2020-11-02 08:11
But we are not solving me but Ralfiii :-)

**Comment by oldman4U** [comment] 2020-11-02 16:29
Hi ralfii.

Not sure if this is already clear to you, but you made everything right. The problem is, that the precompiled firmware is very old and because of this, some elements are missing or wrong in the other parts of the software wich is needed to update your TFT.

Have you ever used VSC and PIO to compile your own firmware? Would you like to do so and would you need any help?

Please let us know

**Comment by oldman4U** [comment] 2020-11-02 16:30
@radek8 And maybe I will get the virus.....amazon.**DE**

;-)

**Comment by radek8** [comment] 2020-11-02 21:52
FW including not yet merged PR 1127 and 1126 :-)

[BIGTREE_TFT35_V3.0_E3.26.x.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/5478258/BIGTREE_TFT35_V3.0_E3.26.x.zip)

**Comment by oldman4U** [comment] 2020-11-02 22:49
BTW. Congrats. Ripper08...

**Comment by radek8** [comment] 2020-11-02 23:05
> BTW. Congrats. Ripper08...

I don't understand some people. He buys a display from China for a few € and waits for a technician to come to install it ....

**Comment by ralfiii** [comment] 2020-11-03 06:05
1000 thanks to everyone!!! What a great, helpful community.
A few hours ago my wife gave birth to a baby,  so I am busy with other
things, but asap I'll try the provided patch...
Thanks again, Ralf

Radek <notifications@github.com> schrieb am Mo., 2. Nov. 2020, 22:52:

**Comment by oldman4U** [comment] 2020-11-03 06:51
Congratulations and all the best for your family!!

**Comment by ralfiii** [comment] 2020-11-04 08:34
Baby is sleeping, so I found a few minutes time:

After updating the firmware with BIGTREE_TFT35_V3.0_E3.26.x.zip provided by Radek8 yeserday, I get an error
"Failed to enable bed leveling".
And the bed leveling zero height using touch is a big higher than using Marlin.
Shouldn't that be identical?

And another question: 
Is the RESULT different, printing through touch or through Marlin? Or is it identical?

**Comment by oldman4U** [comment] 2020-11-04 08:44
Hi. They sleep a lot at the beginning. Try to get some extra sleep also. You will need it the coming 18y. 😁

So update worked?

You should see identical quality prints independent of the user interface you use.

With leveling I can not help. Start a new ticket for each new topic and close unneeded tickets.

**Comment by radek8** [comment] 2020-11-04 11:51
Ripper is the nickname of an arrogant user from another discussion :-)

**Comment by radek8** [comment] 2020-11-04 11:54
Do you use any kind of leveling?
If so, what is your probe?
Do you have leveling points saved?

**Comment by ralfiii** [comment] 2020-11-05 12:20
Hey Radek8!
I don't have any probe (yet, bltouch will follow).
And I didn't know I could save leveling points.
I clicked around in some menus, a "G-code unknown" error occurred. now the
leveling suddenly is on the right height.
The error message still shows when powering up in touchscreen mode.
Maybe for the moment I'll go with Marlin...

Thanks for your effort!
Ralf

Am Mi., 4. Nov. 2020 um 12:54 Uhr schrieb Radek <notifications@github.com>:

**Comment by radek8** [comment] 2020-11-06 22:58
An unknown code is fine if you run an option that your Marlin does not support or is not configured.
It would be good to compile Marlin yourself so that you can adapt Marlin to your configuration as much as possible.

**Comment by radek8** [comment] 2020-11-10 06:04
> The temperature update problem you describe is standard behavior when printing from an SD card integrated on the Marlin board.
> If you print from the SD card on the TFT display, the temperature is updated already during heating.

Allow to start code and add to start code
M155 S1
this could solve the problem with reporting temperatures when printing from SD to SKR

**Comment by radek8** [comment] 2020-11-11 11:01
> 
> Also strange: Is it normal that the GUI doesn't show bed and extruder temperature when heating up for a print job? My display stays as in the screenshot until the print starts, only then the current and expected temperatures are shown.
> 

I have an idea how to solve the problem with updating temperatures when starting printing from the integrated SD card in Marlin.
I tested it yesterday and it works.
I will create a PR. If Bigtreetech approves it, it would be a permanent solution for everyone who suffers from this problem.

**Comment by oldman4U** [comment] 2020-11-11 11:53
This would be great. Do you know why it works on my machine? And whats
about the layer hight which is shown nowhere!?

Radek <notifications@github.com> schrieb am Mi. 11. Nov. 2020 um 12:02:

**Comment by radek8** [comment] 2020-11-11 18:28
> This would be great. Do you know why it works on my machine? And whats about the layer hight which is shown nowhere!? Radek <notifications@github.com> schrieb am Mi. 11. Nov. 2020 um 12:02:

Why do you see temperatures when you warm up the bed and the nozzle when printing from the integrated SD? That would be good to know. I assume your slicer does it. Can you attach a file to a printable work?
Thank you
 
The problem with updating layer height and task completion percentage is a bit bigger. Printing is controlled by Marlin and TFT has no way of knowing which layer to print and what percentage is complete. This would require Marlin to proactively send the press status over the serial line. But at the moment he probably can't do that

**Comment by oldman4U** [comment] 2020-11-11 21:25
Please check out PR #1244 for a possible solution.

Thank you

**Comment by oldman4U** [comment] 2020-11-11 21:36
[CE3_KeyCap_Opener.gcode.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/5526861/CE3_KeyCap_Opener.gcode.zip)

Please find attached the code file which I printed while I made the movie which shows the temp changing while heating: Temp Changing print from SD card.mov.mov.zip #1070

**Comment by radek8** [comment] 2020-11-11 22:14
It's strange.
Same parameters as for me, but different behavior.

**Comment by oldman4U** [comment] 2020-11-12 00:07
What is different?

**Closed** 2020-11-18 06:38 UTC
Labels: bug

**Comment by FoxtrottPL** [comment] 2020-11-22 08:37
About missing bmp files - I solved it by merge all bmp files from unified, normal and hybrid tft folders.
