### ISSUE TITLE
[Bug] Protected Pin error when trying to PID tune bed / Hotend

### ISSUE THREAD

**Issue by Hyrules** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1015] opened 2020-08-22 21:01 UTC
Hi everyone, 

I'm new to the TFT3.5 V3 / SKR 1.4 Turbo community and i'm struggling with a few issue on the TFT3.5 V3.

Whenever I try to do an PID autotune on the TFT screen, (in touch screen mode) it gives me an protected pin error and get stuck in the pid autotune in progress screen. At some point I get a message to save my pid settings but the screen never disappear. Any one has idea what is happening ? Thanks. I'm also using marlin 2.0.6 bug-fix firmware.

**Comment by bigtreetech** [comment] 2020-08-24 09:48
It's because `M42` command in PID menu,  I'll deleted these non generic gcode to avoid similar problems

**Comment by digant73** [comment] 2020-08-24 10:15
> It's because `M42` command in PID menu, I'll deleted these non generic gcode to avoid similar problems

it should be replaced with a standard gcode, if any

**Comment by Hyrules** [comment] 2020-08-24 15:21
Thanks and keep up the good work ! Let me know when If I can test anything.

**Comment by digant73** [comment] 2020-08-24 16:37
Fixed by PR #1014

**Comment by digant73** [comment] 2020-08-26 10:16
> Thanks and keep up the good work ! Let me know when If I can test anything.

the fix is now merged in the BTT main branch. Please, can you verify if now the problem is solved and eventually close this bug request?

**Comment by Hyrules** [comment] 2020-08-26 11:33
I don't have the PID Protected Pin error anymore but I have a mcode error :  M150 R255 U0 B0 when I try to pid tune (tuning does itself anyway)  I don't have a led. The only led I see is in the corner of the screen sometimes. This seems to be ignoring the fact that I put knob_led_color: 0 in the config.ini. Might be related.

**Comment by digant73** [comment] 2020-08-26 11:47
ok the error you got it's due to the standard gcode to change the LED color. However you can ignore it (because you don't have any LED) the PID process should run correctly. The Knob led is another kind of LED

**Comment by Hyrules** [comment] 2020-08-26 11:52
There should be a way to not have this error message at all. maybe silence the error if there is no led. Normally should not produce an error if there is no led.

**Comment by digant73** [comment] 2020-08-26 13:51
I have to see. You should not receive any error if you don't have any LED

**Comment by Hyrules** [comment] 2020-08-26 13:52
Something else has also changed. Now when I want to print, the printer does a bed level before each print which should not happen if I have already a bed leveled. I have to print something else again to confirm that. I will finish my current print in a few hours so I will start something else after.

**Comment by digant73** [comment] 2020-08-26 14:01
I didn't yet installed the new release with the new PRs. I will have a look

**Comment by Hyrules** [comment] 2020-08-26 18:43
Basically yes it does a bed level with every print now.

**Comment by Hyrules** [comment] 2020-08-26 19:13
Edit : Nevermind it's cura... just updated and they changed the startup gcode.

**Comment by oldman4U** [comment] 2020-09-03 06:27
Hi.

What is the status of the reported issue?

**Comment by charakaSamawry** [comment] 2020-09-12 14:36
It seems the auto tune pid throws up an m150 error. I’ve never understood why the defaults assume you purchased extra led lights to go with the tft really? Or have I done something wrong and told it I do have less in the config.ini??

**Comment by digant73** [comment] 2020-09-14 09:14
many printers have a LED close to the nozzle. In a next release that error could be added in the ignore list. However the PID process is not affected in any case.
Can you provide me exaclty the error you got (reported in the terminal)?

**Comment by oldman4U** [comment] 2020-09-26 07:56
@Hyrules 

Could you please answer the question or close the ticket. 

Thank you

**Comment by Hyrules** [comment] 2020-09-26 13:39
I would have to get the latest version of the firmware but the one i'm using with my version is giving the m150 error as well. 
Error is exactly "unkown command M150 R255 U0 B0" I don't have led either on my side

Either the firmware should silently ignore this error or check if there is a led from the config.

**Comment by oldman4U** [comment] 2020-09-27 09:43
Hi. 

digant referenced this issue in a PR which has been merged 7 days ago. So I guess installing the latest firmware will fix the reported issue. Please try and let us know

**Comment by Hyrules** [comment] 2020-09-27 15:27
This is fixed on my side.

**Comment by oldman4U** [comment] 2020-09-27 16:46
Please help the community and close the ticket once you do not need it anymore. Thank you

**Closed** 2020-09-27 17:01 UTC
Labels: question
