### ISSUE TITLE
[BUG] mesh leveling showing wrong point index with bilinear bed leveling

### ISSUE THREAD

**Issue by rightawy** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1469] opened 2021-01-01 05:43 UTC
### Description
with bilinear bed leveling  the mesh editor show the point index as I:1 J:65535 when trying to edit a point and the extruder will not move along the X axis only the **I** values will show correctly.

### Steps to reproduce

1. perform ABL with Bilinear bed leveling
2. go to Mesh editor and try to edit a point.

**Expected behavior**
The indexes should be updated to the actual selected point.

**Actual behavior**
the J index is always 65535

### Hardware Variant
TFT35 v2
### TFT Firmware Version & Main Board Firmware details
updated to latest commit on 31-December-2020
Bilinear leveling enabled on Marlin bugfix from 28-December-2020.

**Comment by digant73** [comment] 2021-01-01 12:54
Which is the grid size? and are the grid values correctly displayed in the mesh editor?

**Comment by guruathwal** [comment] 2021-01-09 04:38
I can confirm this bug.

**Comment by digant73** [comment] 2021-01-09 12:36
Strange because I tested all bl types when I developed the editor. Which grid size have you set in marlin? I will retest it

**Comment by rightawy** [comment] 2021-01-11 02:36
4x3 grid size

**Comment by digant73** [comment] 2021-01-12 18:52
I tested a 5x5, 3x4 and 4x3 grid (bilinear bed leveling on Marlin 2.0.7.2, although not the most recent bugfix version) and I had no problem.
Can you provide me the output for the command M420 V1 T1?

In my printer I got the following result:

SENT: M420 V1 T1
READ: Bilinear Leveling Grid:
READ:       0      1      2
READ:  0 +0.088 +0.060 +0.200
READ:  1 +0.093 -0.003 -0.028
READ:  2 +0.063 -0.020 -0.043
READ:  3 +0.075 +0.060 +0.100
READ: 
READ: echo:Bed Leveling OFF
Bed Leveling OFF
READ: echo:Fade Height 10.00
Fade Height 10.00
READ: ok

**Comment by rightawy** [comment] 2021-01-13 04:59
ok I will share the details

**Comment by rightawy** [comment] 2021-01-14 12:50
This is the data received from printer
```
>>> M420 V1 T1
SENDING:M420 V1 T1
Bilinear Leveling Grid:
      0      1      2      3
 0 +0.000 +0.192 +0.230 +0.230
 1 +0.187 +0.320 +0.437 +0.480
 2 +0.155 +0.297 +0.425 +0.375
echo:Bed Leveling ON
```
![IMG_20210114_181234-01](https://user-images.githubusercontent.com/63956212/104592906-f3c73780-5694-11eb-9d62-76086ca8fb7d.jpg)

**Comment by digant73** [comment] 2021-01-14 15:07
the main difference is the empty line present on my side. Can you confirm that the grid size configured in Marlin FW is 4x3 and not 4x4? See values for GRID_MAX_POINTS_X and GRID_MAX_POINTS_Y in Configuration.h in Marlin FW

**Comment by rightawy** [comment] 2021-01-14 17:02
Yes it is the latest bugfix

**Comment by digant73** [comment] 2021-01-14 19:31
ok, the bug was fixed. After some PRs will be merged, I will open a PR with the fix for that bug plus other features and cleanup

**Closed** 2021-01-21 06:03 UTC
Labels: bug
