### ISSUE TITLE
BTT TFT35 V3.0 is not showing print status with SKR1.4T RRF 3.2.2

### ISSUE THREAD

**Issue by basha318i** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1746] opened 2021-03-19 17:28 UTC
When printing from DWC, the TFT35 doesn't show the print status. it shows the temp changes, but not the print screen.

**Comment by bttguy** [comment] 2021-03-19 18:16
Hi! Did you made the required sys changes mentioned in #1743 
After I set those up, it worked.

**Comment by basha318i** [comment] 2021-03-19 18:46
@bttguy Hey, thanks for the suggestion. I'll re-flash a fresh FW & test since I've been testing with couple of other options like Thor42's FW.
I will keep you posted.

**Comment by basha318i** [comment] 2021-03-19 19:39
@bttguy Thanks again, this worked fine for me, although the pause & stop behaviour is not working. for example if the printer is still heating up & you try to pause, it would show a message "Busy.. still processing..." until it finishes the heat cycle then accepts any commands. While if you try to pause mid-way in the heating cycle from DWC, it would immediately execute the pause.

**Comment by bttguy** [comment] 2021-03-19 21:36
Hmm, thanks for the info, will try to reproduce. This feature is new, and might need some further polish with the help of some real use feedback. @Msq001 Does this a limitation or an user error?
By far now the main branch will be the way to go with RRF, as you can see in #1400 compatibility work has started and going pretty nice.

**Comment by jaysuk** [comment] 2021-03-19 21:50
@basha318i did you add M0 to your end gcode?
Stop.g doesn't get called automatically the same way start.g does

**Comment by bttguy** [comment] 2021-03-19 22:20
@jaysuk Where should the M0 added? Only to the end gcode, or to stop/pause.g as well?

**Comment by Msq001** [comment] 2021-03-20 01:50
> @bttguy Thanks again, this worked fine for me, although the pause & stop behaviour is not working. for example if the printer is still heating up & you try to pause, it would show a message "Busy.. still processing..." until it finishes the heat cycle then accepts any commands. While if you try to pause mid-way in the heating cycle from DWC, it would immediately execute the pause.

In my test(start print from DWC + abort print from TFT, or start print from TFT + abort print from TFT ), Abort printing by the TFT"stop" button will not wait for the temperature to rise, it only waits for RRF to give M27 a "Not SD printing" response, and then TFT exits the "Busy Processing, " menu.

**Comment by bttguy** [comment] 2021-03-22 12:49
@basha318i Did it works for you, have you tested it further?

**Comment by jaysuk** [comment] 2021-03-22 12:54
@bttguy M0 should be added only to the end gcode. M0 causes stop.g to be ran because, unlike start.g, its execution is not automatic
See here for stop.g info https://duet3d.dozuki.com/Wiki/Macros#Section_Start_pause_stop_and_power_fail

**Comment by basha318i** [comment] 2021-03-22 17:03
@bttguy I tested, but still the pause takes a while to be executed.
not sure if I need to modify anything in my TFT config.ini?
I added M0 to the end of my g-code from my slicer settings, but not sure if this is relevant? since the pause is my current issue & the M0 will be executed after the print is finished.

**Comment by basha318i** [comment] 2021-03-22 17:14
@bttguy okay, I just re-flashed again & tested & it's working as it should. I started a print from DWC, paused it from the TFT & it immediately executed the pause & updated the DWC.
Thanks, I think I have a working TFT now.
I also noticed that when I try to print from the TFT, the on-board SD doesn't show the folders I have under /gcode directory correctly. it shows them as files, is that a known issue?

**Comment by bttguy** [comment] 2021-03-22 17:54
@basha318i  Glad it works! There are still features that are missing, like what you mention, files right now only listed without any folder system. For now I tested my screen for the features that should work with the lastest commits, but I will test it for possible missing/not properly working features, and will make a FR, hopefully some dev could help us :)
Until that if you have any positive/negative experience/suggestion/FR regarding RRF comment on #1400 for easier tracking of the compatibility development! If it is working now, you could close this issue, since its working, and discuss the others in #1400 :)

**Comment by basha318i** [comment] 2021-03-22 18:12
@bttguy now while it's printing; it's not updating the values (extruder temp, bed temp, layer height, progress, fan speed..etc) the only thing I can see is the timer, please find the attached photos while it's printing.
![tempImageBKmDiD](https://user-images.githubusercontent.com/555150/112037852-cae57780-8b07-11eb-9a78-27b41c946485.gif)
![tempImageXF1rqh](https://user-images.githubusercontent.com/555150/112037879-d3d64900-8b07-11eb-8bbb-625a06278eec.gif)
![tempImageoFtIPQ](https://user-images.githubusercontent.com/555150/112037898-d8026680-8b07-11eb-94a1-f20106ec0766.gif)

**Comment by basha318i** [comment] 2021-03-22 20:11
it's inconsistent; I tried again & it works fine!
There must be a specific sequence I'm doing that causing this..
![tempImage7qoh6g](https://user-images.githubusercontent.com/555150/112052153-6aab0180-8b18-11eb-8b74-8fa8b0ce95ae.gif)

**Comment by bttguy** [comment] 2021-03-23 17:38
@basha318i Well, I have no idea... It's working fine for me ,with the same release and settings. In which configuration do you use RRF, with a WiFi adapter on with an SBC?

**Comment by basha318i** [comment] 2021-03-23 23:43
I’m using a WiFi adapter.

**Closed** 2021-04-03 14:33 UTC
