### ISSUE TITLE
black screen after updating first phase TFT24 v1.1

### ISSUE THREAD

**Issue by Wow4ik93S** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1685] opened 2021-03-07 17:17 UTC
Hi i have black screen after updating first phase. And it doesn't go any further
sd card 8gb fat32 (D:\BIGTREE_TFT24_V1.1.26.x.bin) (D:\config.ini) (D:\TFT24)

after the reset without sd card still black screen

[TFT24.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/6097594/TFT24.zip)

**Comment by guruathwal** [comment] 2021-03-07 17:52
duplicate of #1684. please close this issue you can follow #1684 for update.

**Closed** 2021-03-07 18:43 UTC
Labels: bug
