### ISSUE TITLE
Tft35 v3.0.24.2 update problem

### ISSUE THREAD

**Issue by josephsaathoff** [bigtreetech/BIGTREETECH-TouchScreenFirmware#169] opened 2019-11-17 04:09 UTC
It seems that the icons and fonts are not uploading to the screen. Have white icons and unable to read the writing.

**Comment by ipatch** [comment] 2019-11-19 18:16
I've noticed something similar when updating the FW for my tft35v2 this morning, all the icons on the default "home" screen have a certain fuzzyness to them, but if click in _(press menu)_ from the "home" screen all the icons from within the _menu_ button appear to render as they should the below gif is an example of what I'm describing above.

##

<div align="center">

![tft35v2-icon-issue](https://github.com/ipatch/Marlin/blob/ipatch/build-marlin-2.x/media/btt-tft35v2-icon-render-error.gif?raw=true)

</div>

**Comment by guruathwal** [comment] 2019-11-20 03:34
You need to update your icons. There are new icons for the status screen which needs to be updated on the TFT.

**Comment by ipatch** [comment] 2019-11-20 18:06
~~do i need to copy both folders to the root of the SD card along with the bin or just one folder?~~

```
Copy to SD Card root directory to update - Unified Menu Material theme~~
Copy to SD Card root directory to update~~
```

... should have read the instructions more clearly 🤦‍♀️

##

**leaving this here for future me** _the contents for the sd card should look like the following if lcd = tft35v2

<img width="808" alt="sd-card-root-contents" src="https://user-images.githubusercontent.com/613805/69265103-3c1cbf80-0b8e-11ea-9882-5fcb557ef3f0.png">

**Comment by guruathwal** [comment] 2019-11-20 18:09
you need to rename the `TFT35.CUR` folder to `TFT35`

**Comment by ipatch** [comment] 2019-11-20 19:02
yeah that was the contents of the dir after i flashed.

**Comment by guruathwal** [comment] 2019-11-20 19:04
👍🏼👍🏼 you can close the issue now if the problem is solved.. :)

**Comment by ipatch** [comment] 2019-11-20 19:41
unfortunately it's not my issue to close, i was just commenting on it.

**Comment by guruathwal** [comment] 2019-11-21 05:00
@ipatch Well then we have to wait for @josephsaathoff to confirm..

**Comment by josephsaathoff** [comment] 2019-11-21 06:46
My issue was as card too big and was not formatted to fat32

**Closed** 2019-11-21 06:46 UTC
