### ISSUE TITLE
[FR] CHAMBER temperature

### ISSUE THREAD

**Issue by DrumClock** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1182] opened 2020-10-18 14:07 UTC
Please be able to display BED and CHAMBER temperature alternately.

![IMG_20201018_160351.jpg](https://user-images.githubusercontent.com/64655979/96369757-0399b300-115c-11eb-86b1-1cbc202080fb.jpg)

**Comment by oldman4U** [comment] 2020-10-18 21:55
hi.

This is a duplicate of #707 where the user was not able to give the ticket a useful title and now he is not able to close the ticket or change the title.

Please close the ticket. This feature request is on the FR list which I will post very soon.

Thank you

**Comment by bigtreetech** [comment] 2020-10-19 14:29
Hello, In fact, it has been supported since https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/pull/875
If CHAMBER is enabled in Marlin, a switching state of CHAMBER will be automatically added in the heater menu of touch screen, and the actual temperature and target temperature of CHAMBER will also be displayed on the top title bar.

**Comment by DrumClock** [comment] 2020-10-19 14:37
Yes, this is the case, but is it possible to display BAD and CHAMBER temperatures 
alternately in the same way as for NOZZLE T0 and T1?

**Comment by oldman4U** [comment] 2020-10-19 14:45
DrumClock.

@bigtreetech - welcome back, we missed you!;-)

Personally I do not use a heated Chamber, but from BTT's answer I would expect that this already works as expected in case everything is setup right in Marlin.

**Comment by DrumClock** [comment] 2020-10-19 14:56
Yes, in the "Heat" menu, the Chamber is fine.
I wanted the temperature to be shown on the home screen and on the screen when printing alternately with the temperature for
"BED" as with the  `nozzle T0 / T1`, `Fan F0 / F1` and `Speed / Flow `icons

**Is it already understandable?**

**Comment by bigtreetech** [comment] 2020-10-19 14:59
Yes, I understand. You want to alternate bed and chamber on the status screen

**Comment by oldman4U** [comment] 2020-10-19 19:18
No idea if this is already possible or not, but could you please activate this in config.ini and update your TFT or activate this directly in the feature list of the TFT to see if you can see the Chamber temp there.

#### Persistent temperature info
# show persistent temperature info on all menu screens
# Options: [enable: 1, disable: 0]
persistent_info:**1**

Please let me know

**Comment by DrumClock** [comment] 2020-10-19 19:32
Hi @oldman4U 
No change, the temperature CHAMBER z is displayed only in the corner of the screen but it works even without setting.

**Comment by oldman4U** [comment] 2020-10-19 19:50
Could you pls add a picture which shows this.

Thank you

**Comment by DrumClock** [comment] 2020-10-19 20:13
Hi @oldman4U there are ..
![1_](https://user-images.githubusercontent.com/64655979/96506615-3aed8a00-1258-11eb-914d-72d5282feddd.jpg)
![2_](https://user-images.githubusercontent.com/64655979/96506618-3cb74d80-1258-11eb-8473-eb93ab50a70c.jpg)
![3_](https://user-images.githubusercontent.com/64655979/96506620-3d4fe400-1258-11eb-84b5-7b92ccfba650.jpg)
![4_](https://user-images.githubusercontent.com/64655979/96506623-3de87a80-1258-11eb-8dd6-ca325a591f4a.jpg)
![5_](https://user-images.githubusercontent.com/64655979/96506624-3f19a780-1258-11eb-8650-2886e7128756.jpg)
![6_](https://user-images.githubusercontent.com/64655979/96506626-3fb23e00-1258-11eb-88f1-d16497332630.jpg)

**Comment by oldman4U** [comment] 2020-10-19 21:26
OK. Picture 3 and 4 shows clearly that the Chamber is recognised correctly. So you should see the Bed and Chamber Temp. alternating - which is not the case. You can leave it a feature request and I will add it to the FR list instead of 707, or you change it to a Bug. Whatever fits better for you.

**Comment by DrumClock** [comment] 2020-10-20 06:43
OK, add it to the FR list instead of 707
Thanks

**Comment by oldman4U** [comment] 2020-10-20 20:33
Done.

Please check #1170 and close this ticket afterwards.

Thank you

**Comment by oldman4U** [comment] 2020-10-21 14:51
Hi.

I verified this also on my printer, even I have no chamber. Turning it on there is a chamber in the upper right corner, but the Bed does not changed to show the chamber. According to BTT this should work, so maybe it would even be best to change this from FR to Bug!?

Again, as you like;-)

**Comment by DrumClock** [comment] 2020-10-21 15:07
Hi @oldman4U 
So can you please change it to BUG?

**Comment by oldman4U** [comment] 2020-10-21 15:27
You are the owner, so only you can change it.

I will keep it also in the feature requests because it is unclear if it is A or B.

**Comment by DrumClock** [comment] 2020-10-21 15:30
how do I change `[FR] CHAMBER temperature # 1182 `to **BUG**?

**Comment by oldman4U** [comment] 2020-10-22 13:49
@radek8

Can you please help with this issue. At least to find out if this is a bug or not implemented. 

Thank you

**Comment by radek8** [comment] 2020-10-22 16:24
Hello
it is not implemented to be displayed on both status screens. only in the corner of the display.
This is what he would like to program.

**Comment by oldman4U** [comment] 2020-10-22 17:05
Cool. So it is a feature request.

Thank you Radek

Radek <notifications@github.com> schrieb am Do. 22. Okt. 2020 um 18:24:

**Comment by oldman4U** [comment] 2020-10-23 21:25
I checked the bmp's and there is nothing for Chamber, so it has never been implemented.

@DrumClock 

It is listed in the FR list. Could you please close this ticket and I will try to find an engineer to look at it.

Thank you

**Closed** 2020-10-24 10:37 UTC
Labels: enhancement
