### ISSUE TITLE
[Q] MKS TFT35 V1.0 install firmware

### ISSUE THREAD

**Issue by stef-ladefense** [bigtreetech/BIGTREETECH-TouchScreenFirmware#2719] opened 2023-02-16 14:53 UTC
Hi,
I'm trying to install the latest firmware on a MKS TFT3**5** V1.0.
I followed the doc, renamed the MKS_TFT35_V1_0.27.x.bin file to mkstft35.bin, copied the TFT35 folder and the config.ini and copied everything to a 4GB SD.
the sequence begins then a progress bar reaches 100% and nothing more happens.
do you have an idea ?
Thanks a lot

**Comment by digant73** [comment] 2023-02-16 17:06
if you have a MKS TFT32 v1.4 you must use `MKS_TFT32_V1.4.27.x.bin` renamed to `MKSTFT32.bin` and the `TFT28` folder renamed to `TFT32` in order it can be recognized and installed by the TFT.

**Comment by stef-ladefense** [comment] 2023-02-16 18:25
Sorry, I made a typo
title : [Q] MKS TFT3**5** V1.0 install firmware
I'm trying to install the latest firmware on a MKS TFT3**5** V1.0.

it does not change the result, progress bar to 100% and no more reaction

**Comment by stef-ladefense** [comment] 2023-02-17 09:30
I copied the following files to the card
config.ini
MKS_TFT35_V1_0.27.x.bin renames MKSTFT35.bin
TFT35

and here are the progress pictures.

![20230217_101714](https://user-images.githubusercontent.com/43587190/219605995-7a03514c-49de-4ce0-99f0-fab303638300.jpg)

it hangs at 100% and after a reset, it does not boot

![20230217_102110](https://user-images.githubusercontent.com/43587190/219606148-82892c0e-5c39-4daf-90fc-c52a1dba57c8.jpg)

I place the photos of the MKS card

![20230217_101458](https://user-images.githubusercontent.com/43587190/219606516-01e8aee3-c016-4301-8381-6b804bbc2f8d.jpg)
![20230217_101413](https://user-images.githubusercontent.com/43587190/219606543-39aa5e98-2e47-40c5-9a4d-5e5a86ed2a73.jpg)

**Comment by rondlh** [comment] 2023-02-19 12:11
The MKS TFT35 V1.0 will erase all settings when you flash a new firmware, this might be the cause, perhaps it's in Marlin mode?
You could try to update the settings with a correct config.ini
Does the TFT rename your config.ini?

**Comment by stuclem47** [comment] 2023-02-19 14:21
Following this with interest.
I have exactly the same issue.
The file config.ini remains on the SD Card unchanged, as does the TFT35 folder.
Firmware file is renamed to: MKSTFT35.CUR

**Comment by stuclem47** [comment] 2023-02-20 11:52
I am coming to the conclusion that the firmware MKS_TFT35_V1_0.27.x.bin is not suitable for this model. I have tried flashing alternate bootloaders that have been suggested as workinfg elsewhere, but after this the firmware flash still fails.
There are several different models of MKS TFT35 screens, and this may be for one of the other models.
Has anyone actually got the BTT firmware loaded on this particular model?

**Comment by stuclem47** [comment] 2023-02-20 20:38
The MKS_TFT35_V1_0.27.x.bin (renamed as MKSTFT35.bin) flashes and shows progress to 100% and goes no further. File is renamed as MKSTFT35.CUR. It seems to looking for the mks_font & mks_pic folders and the mks_config.txt file, which are not part of the BTT package.

**Comment by stuclem47** [comment] 2023-02-20 22:20
Update:
Flashed open source bootloader from here: https://github.com/darkspr1te/mkstft35_V1_open_bootloader
Reamed the BTT file to mkslcd.bin as instructed there and added config.ini and TFT35 folders. The flash completed showing the icons on screen as they were uploaded, just like when my BTT TFT is updated. Then went to touch screen calibration, once this was completed it loaded a screen with just  one line of garbled text. Getting closer!

**Comment by rondlh** [comment] 2023-02-21 11:03
I just tried the conversion of a Original MKS TFT35 V1.0 (FW 1.0.7) to the 2023 Feb 16 BTT firmware.
All went as expected. Here the contents of my SD Card.
MKSTFT35.bin is the renamed MKS_TFT35_V1_0.27.x (CRC 01490B3F, 2023 Feb 16).
The TFT35 holds the files in "\Copy to SD Card root directory to update\THEME_Unified Menu Material theme\TFT35", both bmp and font directories.
![SD Folder](https://user-images.githubusercontent.com/77279634/220323918-97fba0ce-5470-4588-9d32-73026a759397.png)

Flashing worked as expected, all files and the dir get the extension ".CUR" added.

![Before Update](https://user-images.githubusercontent.com/77279634/220325778-ac870a3a-3d5b-4549-804c-d52e06cb97ec.jpg)

![After Update](https://user-images.githubusercontent.com/77279634/220325793-460aeb7c-0be4-4250-bce3-f827e3a8b854.jpg)

You could try another SD card, and make sure it's not write protected, that could cause issues.
darkspri1te is the creator of the MKS TFT35 V1.0 port of the BTT firmware, which is greatly appreciated!

I'm not sure if I'm allowed to post the original MKS TFT35 V1.0 bootloader here, I have both the original version and a version I patched so you don't need to "encrypt" the firmware anymore. If you use the wrong version the application will not work (black screen), but it has no effect on the flashing process.

**Comment by stef-ladefense** [comment] 2023-02-21 12:11
> I have the MKS TFT35 V1.0, from the picture I would say it's exactly the same. I can give it a try. One of the pictures shows "Firmware: 1.0.8", that's the original MKS firmware, not the BTT hosted here. It will NOT handle the BTT config.ini and BTT Icons.

hi,
it's pics of card BEFORE flash with this BTT firmware

**Comment by stef-ladefense** [comment] 2023-02-21 12:38
Hi,
I took the files like you, and same problem, 100% blocking without follow-up.
I then compiled the firmware (I had everything after my fix for the TFT32LV3.0) and I generated a 'MKS_TFT35_V1_0.27.x_encrypted.bin' file.
once renamed to 'MKSTFT35.bin' and copied to the SD, the update to the BTT firmware went through correctly.

![20230221_133124](https://user-images.githubusercontent.com/43587190/220346177-13b5cbb1-669e-4930-80e7-4ab19faa35dc.jpg)

https://github.com/stef-ladefense/BIGTREETECH-TouchScreenFirmware/commit/34195b95e86b7e9a67743f4edec6553ff0d2ef69

**Comment by rondlh** [comment] 2023-02-21 14:06
@stef-ladefense That's great news! Thanks for reporting back.

**Comment by stuclem47** [comment] 2023-02-21 15:29
@stef-ladefense 
Can you make a copy of the MKS_TFT35_V1_0.27.x_encrypted.bin file available?

**Comment by stef-ladefense** [comment] 2023-02-21 15:44
> @stef-ladefense Can you make a copy of the MKS_TFT35_V1_0.27.x_encrypted.bin file available?

allready in my github for moment
https://github.com/stef-ladefense/BIGTREETECH-TouchScreenFirmware/tree/master/Copy%20to%20SD%20Card%20root%20directory%20to%20update

**Comment by stuclem47** [comment] 2023-02-21 16:22
Thank you @stef-ladefense 
I have now flashed the firmware successfully.

**Comment by digant73** [comment] 2023-02-21 16:40
the binary MKS_TFT35_V1_0.27.x.bin provided in this repo is the unencrypted version although I provided also the encrypted one. Currently, for the encrypted version you have to compile it by yourself as you did

**Comment by oldman4U** [comment] 2023-02-21 20:53
Please update the Readme if you would like to keep this information available for other users. Thank you

**Comment by rondlh** [comment] 2023-02-23 17:17
> the binary MKS_TFT35_V1_0.27.x.bin provided in this repo is the unencrypted version although I provided also the encrypted one. Currently, for the encrypted version you have to compile it by yourself as you did. Please close the ticket if you solved your issue.

I recommend to provide the encrypted FW by default, as that is what most users need.

**Comment by digant73** [comment] 2023-02-24 11:38
@rondlh fixed in #2728

**Closed** 2023-04-11 09:38 UTC
Labels: question
