### ISSUE TITLE
Thumbnail visibility for Prusaslicer

### ISSUE THREAD

**Issue by neew1** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1238] opened 2020-11-08 13:01 UTC
Hi Guys,

first of all, many thanks for your effort.

The Cura plugin for the thumbnails is great, but I actually use the Prusaslicer. Is there such a plugin or something for this one?

According to the Internet, you can (like the Mini) add the item Thumbnail to the corresponding printer profile via Prusaresearch.ini.
But I can't get the thumbnail to be displayed. can someone help me?
Hardware:
SKR 1.4 Turbo and Btt TFT35 V3.0

friendly greetings

**Comment by oldman4U** [comment] 2020-11-08 15:01
Hi.

I added your feature request to the pinned FR list #1170 . This list has been made so that users which would like to contribute have a single point where they can look for FR and BUGs. This also allows to make sure, that only a single developer works on a certain feature and not several developers - like we had in the past.

It would be great if you could close this ticket. This would allow us to keep this system maintainable.

Thank you and happy printing

**Comment by traffic-light** [comment] 2020-11-09 14:58
Hi, Good idea. But it's not possible to create a plugin for prusaslicer. Then there should be a edited version of prusaslicer which they've to maintain. And that's the hard part...

**Comment by neew1** [comment] 2020-11-09 15:32
It's a shame, I like to work with the slicer because I always had problems with Cura. So many little things that were simply not available with the Prusaslicer.
But today with these screens it should soon be standard. Hopefully

**Comment by oldman4U** [comment] 2020-11-09 15:51
I do not know who finally made the functionality, BTT or a user or someone got paid for it, I do not know. But I could imagine, that they finally followed simply the majority of users and this seems to be 80% plus for Cura.

This is open source, the way is clear, one already walked down the road and now someone else has to go the same way. What the community delivers is what we all can use. There is no manufacturer we can blame or ask to do it.

You can use Prusaslicer and there is nothing wrong with it, but you get the functions which are available for it and those using Cura get the other functions. It is great that there is a choice, isn't it!?

**Comment by neew1** [comment] 2020-11-09 19:36
Sure, of course,
It's a shame anyway;) of course a plus for Cura.
But it's also a shame that I don't know my way around here and can't do anything like programming either.

I wanted to ask if there is something like that and / or someone of you could do something like that, but I also can't estimate the effort.

Since I just manage to configure Marlin to print.

And the most important thing is that with each success, the fun of the thing increases.

And excuse my "English" that is translated from g ....;)

Happy printing

**Comment by oldman4U** [comment] 2020-11-09 20:47
I mean this is a nice to have feature finally and not a must have. Even not all Cura users use this function and use the list view instead.

Maybe one day there will be a similar function for Prusa also, or you give Cura a second try and you decide again afterwards.

**Comment by traffic-light** [comment] 2020-11-09 22:29
![image](https://user-images.githubusercontent.com/37051137/98604156-77565800-22e3-11eb-9fa6-d62dd7071824.png)

**Comment by neew1** [comment] 2020-11-10 06:16
Oh really?
would that mean that there is a way to possibly set this for the Prusaslicer.

how could i do that

excuse the question.

Kind regards

**Comment by bigtreetech** [comment] 2020-11-10 06:34
Does anyone know the encoding format of prusaslicer thumbnail? Or related document links? another point to consider is whether the resolution of prusaslicer thumbnail can be set. Otherwise, we can't confirm that all TFTs are compatible

**Comment by traffic-light** [comment] 2020-11-10 07:08
I don't know. But I can test or send the file to you @bigtreetech

**Comment by traffic-light** [comment] 2020-11-10 12:35
@bigtreetech I received an awnser:

As answer to Bigtreetech

 

The thumbnail-data from PusaSlicer is a base64 encodet 256 color png.

 

And you can see in my phyton script it writes all four tumbnail sizes to the gcode file

 

def overseek(gfile):

        outdatar = ""

        outdatar = outdatar + overread(QSize(70,70),gfile)

        outdatar = outdatar + overread(QSize(95,80),gfile)

        outdatar = outdatar + overread(QSize(95,95),gfile)

        outdatar = outdatar + overread(QSize(160,140),gfile)

        return outdatar

 

Marc

**Comment by neew1** [comment] 2020-11-10 19:22
So what does that mean exactly?

Can this be inserted anywhere?

excuses these questions,

**Comment by ETE-Design** [comment] 2020-11-11 00:43
@traffic-light So to get this working we need to add it as an Post Processing Script?

**Comment by traffic-light** [comment] 2020-11-16 21:14
[biqu_convert_new.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/5549789/biqu_convert_new.zip)

This is the file for thumbnail in prusaslicer.

I don't know how it works. I don't care enough about it at this moment to research it ;-)

**Comment by effgarces** [comment] 2021-01-01 13:30
This works rather nicely, thanks for the script. I already made a small change to it, as it sits now, it saves whatever gcode file it receives with `[Bigtree].gcode` appended to the end of it. I modified it so it simply adds `_btt` (a little bit smaller) and it preserves the original file extension, instead of enforcing `.gcode`:
[biqu_convert_mod.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/5758960/biqu_convert_mod.zip)

How to use:
Download and install python 3 (3.9.1 at this moment in time), afterwards, install PyQt5, by going to the command line and issuing `pip install PyQt5`

Next open prusa slicer and add the thumbail generation:
![Captura de ecrã 2021-01-01 124431](https://user-images.githubusercontent.com/1185683/103439342-fad15d00-4c33-11eb-97ca-65bbb512ba31.png)
 

Finaly go to your Print Settings and in Post processing scripts, add the following [python absolute path] [space] [script absolute path] and if any of the paths contain spaces enclose them in "":
![Captura de ecrã 2021-01-01 131206](https://user-images.githubusercontent.com/1185683/103439357-176d9500-4c34-11eb-86e9-630646848e63.png)

Then when saving the gcode, it will be processed by the script that will replace it with a version with the correct thumbnails for our TFT

**Comment by sarvenn** [comment] 2021-01-10 11:51
@effgarces I tried you instruction but could not go further then installing pyton.
I'm quite far from using pyton, coding etc.
Is it possible to provide a plug and play file? Run and go.
I tried the cura plugin which works great. Now I use prusaslicer and I would be happy to get thumbnail from prusaslicer as well.

**Comment by effgarces** [comment] 2021-01-10 15:50
@sarvenn  I've created a repo with the modded version that I shared above and also "compiled" a windows standalone version, using auto-py-to-exe, if you are on windows give it a try, seems to be working for me.
Grab it here: https://github.com/effgarces/Biqu-Thumbnail-Generator/releases/tag/0.01

**Comment by sarvenn** [comment] 2021-01-10 21:28
Great! Thank you. I'll try it tomorrow and inform you.

**Comment by sarvenn** [comment] 2021-01-12 12:01
> @sarvenn I've created a repo with the modded version that I shared above and also "compiled" a windows standalone version, using auto-py-to-exe, if you are on windows give it a try, seems to be working for me.
> Grab it here: https://github.com/effgarces/Biqu-Thumbnail-Generator/releases/tag/0.01
> With this standalone version you shouldn't have to install python or pyqt, simply copy the exe to the prusalicer.exe or superslicer.exe folder and add the following to the post processing scripts section:
> ![Captura de ecrã 2021-01-10 155118](https://user-images.githubusercontent.com/1185683/104127733-b8a6ca80-535b-11eb-8a4d-f27d1bcefb2e.png)

@effgarces I tried your solution above recently. It works perfectly. Thank you very much.
I think your solution should drive PrusaSlicer developers to integrate this into slicer software.
How can we take their attention?

**Comment by 3dfixer** [comment] 2021-01-17 15:24
works for me. 
when printing from tft it also replaces babystepping icon with the picture!

**Comment by effgarces** [comment] 2021-01-17 16:15
> > @sarvenn I've created a repo with the modded version that I shared above and also "compiled" a windows standalone version, using auto-py-to-exe, if you are on windows give it a try, seems to be working for me.
> > Grab it here: https://github.com/effgarces/Biqu-Thumbnail-Generator/releases/tag/0.01
> > With this standalone version you shouldn't have to install python or pyqt, simply copy the exe to the prusalicer.exe or superslicer.exe folder and add the following to the post processing scripts section:
> > ![Captura de ecrã 2021-01-10 155118](https://user-images.githubusercontent.com/1185683/104127733-b8a6ca80-535b-11eb-8a4d-f27d1bcefb2e.png)
> 
> @effgarces I tried your solution above recently. It works perfectly. Thank you very much.
> I think your solution should drive PrusaSlicer developers to integrate this into slicer software.
> How can we take their attention?

I really doubt that the prusaslicer developers would integrate this solution as it sits right now. The best approach would probably be rewrite it in c++ and do a pull request on the prusaslicer github but even then I'm not sure if they would be willing to integrate it. Maybe the superslicer developers would be more open to that integration.

**Comment by effgarces** [comment] 2021-01-17 16:24
> works for me.
> when printing from tft it also replaces babystepping icon with the picture!

Yeah, I've also noticed that. The weird is that if start a print from wifi, using esp3d, the picture is missing. Probably a bug in the touchscreen firmware.

**Comment by sarvenn** [comment] 2021-01-19 10:21
@effgarces as you guessed superslicer developers are interested but prusaslicer developer suggested to change BTT's thumbnail view format. Actually it is an another solution may be but this time there Cura will also need to change it's relevant plugin.
Anyway, you solved the problem. Thanks again mate. I wish I knew coding as well to help the community.

**Comment by gordo3di** [comment] 2021-02-06 15:47
Works great! Thank you. I believe it's supposed to replace the babystepping icon intentionally otherwise there's nowhere else to display it.

**Comment by neew1** [comment] 2021-03-01 19:44
Thank you  a lot, this works so nice.
great work.

thanks

**Comment by bttguy** [comment] 2021-03-12 02:28
Nice sollution, thank you!

**Comment by marcotagliabo** [comment] 2021-04-07 14:54
Hi to All...  Someone have done this python "trick" with MacOS?  i've tried but PrusaSlicer get error compiling g-code

Post-processing script /Library/Frameworks/Python.framework/Versions/3.9/bin/python3.9 "/Library/Frameworks/Python.framework/Versions/3.9/bin/biqu_convert_new.py" on file /var/folders/jj/bk768xgs5lsg_r6rrjgj6fgw0000gn/T/.PrusaSlicer.upload.265f-b320-6b5d-a7a7 failed.
Error code: 1
Output:
Python path configuration:
PYTHONHOME = '/Users/marcotagliabo/Library/Application Support/Autodesk/webdeploy/production/aea9db95b176b4e876666d6d1c364de9e4dfc5b8/Autodesk Fusion 360.app/Contents/Frameworks/Python.framework/Versions/Current'
PYTHONPATH = '/Users/marcotagliabo/Library/Application Support/Autodesk/webdeploy/production/aea9db95b176b4e876666d6d1c364de9e4dfc5b8/Autodesk Fusion 360.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.7/site-packages'
program name = '/Library/Frameworks/Python.framework/Versions/3.9/bin/python3.9'
isolated = 0
environment = 1
user site = 1
import site = 1
sys._base_executable = '/Library/Frameworks/Python.framework/Versions/3.9/bin/python3.9'
sys.base_prefix = '/Users/marcotagliabo/Library/Application Support/Autodesk/webdeploy/production/aea9db95b176b4e876666d6d1c364de9e4dfc5b8/Autodesk Fusion 360.app/Contents/Frameworks/Python.framework/Versions/Current'
sys.base_exec_prefix = '/Users/marcotagliabo/Library/Application Support/Autodesk/webdeploy/production/aea9db95b176b4e876666d6d1c364de9e4dfc5b8/Autodesk Fusion 360.app/Contents/Frameworks/Python.framework/Versions/Current'
sys.platlibdir = 'lib'
sys.executable = '/Library/Frameworks/Python.framework/Versions/3.9/bin/python3.9'
sys.prefix = '/Users/marcotagliabo/Library/Application Support/Autodesk/webdeploy/production/aea9db95b176b4e876666d6d1c364de9e4dfc5b8/Autodesk Fusion 360.app/Contents/Frameworks/Python.framework/Versions/Current'
sys.exec_prefix = '/Users/marcotagliabo/Library/Application Support/Autodesk/webdeploy/production/aea9db95b176b4e876666d6d1c364de9e4dfc5b8/Autodesk Fusion 360.app/Contents/Frameworks/Python.framework/Versions/Current'
sys.path = [
'/Users/marcotagliabo/Library/Application Support/Autodesk/webdeploy/production/aea9db95b176b4e876666d6d1c364de9e4dfc5b8/Autodesk Fusion 360.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.7/site-packages',
'/Users/marcotagliabo/Library/Application Support/Autodesk/webdeploy/production/aea9db95b176b4e876666d6d1c364de9e4dfc5b8/Autodesk Fusion 360.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python39.zip',
'/Users/marcotagliabo/Library/Application Support/Autodesk/webdeploy/production/aea9db95b176b4e876666d6d1c364de9e4dfc5b8/Autodesk Fusion 360.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.9',
'/Users/marcotagliabo/Library/Application Support/Autodesk/webdeploy/production/aea9db95b176b4e876666d6d1c364de9e4dfc5b8/Autodesk Fusion 360.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.9/lib-dynload',
]
Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
Python runtime state: core initialized
ModuleNotFoundError: No module named 'encodings'
Current thread 0x0000000115a0edc0 (most recent call first):
<no Python frame>

**Comment by bttguy** [comment] 2021-04-10 23:36
@bigtreetech Any possible implementation of native PS thumbnail images without a post processing script?

**Comment by bigtreetech** [comment] 2021-04-12 02:55
> @bigtreetech Any possible implementation of native PS thumbnail images without a post processing script?

Not available yet.

**Comment by oldman4U** [comment] 2021-04-26 09:29
Cura offers what you want.

**Comment by oldman4U** [comment] 2021-06-05 05:14
Good morning. 

I hope you all have seen PR#1973 from user @Cyberdeck which includes the requested feature.

**Comment by gordo3di** [comment] 2021-06-07 14:04
> Good morning.
> 
> I hope you all have seen PR#1973 from user @CyberDeck which includes the requested feature.

Awesome thanks @oldman4U and @cyberDeck !

**Comment by oldman4U** [comment] 2021-06-07 14:27
Cyberdeck did everything I only let you know.

But feedback would be very welcome I believe.

So happy testing

👍🏻

**Closed** 2021-06-11 06:13 UTC
Labels: enhancement

**Comment by sarvenn** [comment] 2021-12-25 12:36
@effgarces hi,
I switched to PrusaSlicer 2.4 beta 1 (final release version does not work on my PC). I used your standalone scripts. It doesn't work. It still works on PS 2.3.3.

This is the error pop up from PS 2.4.0 beta1
![image](https://user-images.githubusercontent.com/66178082/147384915-6367ada2-0f20-4ebe-813a-e7e88211abb7.png)

**Comment by effgarces** [comment] 2021-12-25 13:14
I just took a look at this and from my understanding the expected behavior for post-processing scripts changed with prusaslicer 2.4, now the scripts are expected change the g-code in place and not delete/rename the final file. I will see if I can find the documentation on how to properly comply with this and see If I can fix it.

**Comment by sarvenn** [comment] 2021-12-25 14:27
> I just took a look at this and from my understanding the expected behavior for post-processing scripts changed with prusaslicer 2.4, now the scripts are expected change the g-code in place and not delete/rename the final file. I will see if I can find the documentation on how to properly comply with this and see If I can fix it.

Thanks @effgarces.
Your solution was the best working solution for me.

**Comment by effgarces** [comment] 2021-12-26 14:32
I've updated the script to comply with PrusaSlicer 2.4, the modified version can be found over at https://github.com/effgarces/Biqu-Thumbnail-Generator/ , there's also a "compiled" standalone version, like previously.

**Comment by carlosjln** [comment] 2021-12-28 03:25
@effgarces thanks for updating it 🙏

**Comment by cronos45** [comment] 2022-01-13 23:07
> I've updated the script to comply with PrusaSlicer 2.4, the modified version can be found over at https://github.com/effgarces/Biqu-Thumbnail-Generator/ , there's also a "compiled" standalone version, like previously.

Any idea how I could implement this on Mac OS?

**Comment by lauchablanca** [comment] 2022-02-03 03:32
> > Actualicé el script para cumplir con PrusaSlicer 2.4, la versión modificada se puede encontrar en https://github.com/effgarces/Biqu-Thumbnail-Generator/ , también hay una versión independiente "compilada", como antes.
> 
> ¿Alguna idea de cómo podría implementar esto en Mac OS?

Hola, no puedo encontrar la versión compilada. Sólo el archivo PY. Podrías revisarlo?

**Comment by effgarces** [comment] 2022-02-03 08:50
> > I've updated the script to comply with PrusaSlicer 2.4, the modified version can be found over at https://github.com/effgarces/Biqu-Thumbnail-Generator/ , there's also a "compiled" standalone version, like previously.
> 
> Any idea how I could implement this on Mac OS?

For the Mac you will probably need something like py2app (https://py2app.readthedocs.io/en/latest/) in order to "compile" a standalone version

**Comment by effgarces** [comment] 2022-02-03 08:51
> > > Actualicé el script para cumplir con PrusaSlicer 2.4, la versión modificada se puede encontrar en https://github.com/effgarces/Biqu-Thumbnail-Generator/ , también hay una versión independiente "compilada", como antes.
> > 
> > 
> > ¿Alguna idea de cómo podría implementar esto en Mac OS?
> 
> Hola, no puedo encontrar la versión compilada. Sólo el archivo PY. Podrías revisarlo?

Check the releases area

**Comment by supermerill** [comment] 2022-02-16 18:42
Hi, can someone tell me what's wrong with this 95x95 thumbnail in this file:
[Shape-Box_bqu.gcode.txt](https://github.com/supermerill/SuperSlicer/files/8082187/Shape-Box_bqu.gcode.txt)

I'm trying to implement the thumbnail format natively.

**Comment by sarvenn** [comment] 2022-02-17 17:21
> Hi, can someone tell me what's wrong with this 95x95 thumbnail in this file: [Shape-Box_bqu.gcode.txt](https://github.com/supermerill/SuperSlicer/files/8082187/Shape-Box_bqu.gcode.txt)
> 
> I'm trying to implement the thumbnail format natively.

@effgarces , @CyberDeck , @bigtreetech , @Msq001 , @traffic-light hi guys, could you help @supermerill on his study please?
I did my best but could not help him further. ( https://github.com/supermerill/SuperSlicer/issues/887)

**Comment by sarvenn** [comment] 2022-02-21 14:45
Kind reminder guys.
@effgarces , @CyberDeck , @traffic-light

**Comment by effgarces** [comment] 2022-02-21 20:55
I'm sorry, but right now is a really bad time for me, I really don't have much time at the moment, maybe in two to three days but not guarantees.

**Comment by alejandrojrey** [comment] 2022-05-16 17:52
Hi, is there any way to preserve colors in the preview as the cura plugin does?

**Comment by Nudekz** [comment] 2024-02-15 07:02
![image](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/assets/160106110/4c38359b-0a23-485a-937a-aeea2b15ccea)
Hi, im getting this error, any sugestions?

**Comment by emguepo** [comment] 2024-04-26 16:00
> ![image](https://private-user-images.githubusercontent.com/160106110/304979393-4c38359b-0a23-485a-937a-aeea2b15ccea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxNDY4MjksIm5iZiI6MTcxNDE0NjUyOSwicGF0aCI6Ii8xNjAxMDYxMTAvMzA0OTc5MzkzLTRjMzgzNTliLTBhMjMtNDg1YS05MzdhLWFlZWEyYjE1Y2NlYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyNlQxNTQ4NDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YWRlNDQ5MzY2NTBkZTBkOWNiNGE3NmNkMGM2ZjIwNjVjZjQ1OWE3NjJkZTg0Mzk1ZjUzOTE2NTU2MzdlYTAzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.dswHSPGLjOoj1_7VrtIvthRK3DGmOup8WWGfzCkZWNU) Hi, im getting this error, any sugestions?

Tengo el mismo problema. tanto en Prusa (que reconoce .exe) como en Orca (reconoce  "C:\Python\python.exe" "D:\biqu_convert_new.py";) . 

El archivo que queda en temporales con extension .pp, es reconocido por la impresora y muestra la miniatura...

![Captura de pantalla 2024-04-26 105614](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/assets/88221675/e93bf266-ec1f-4dda-bfe4-3e278559d5db)
![Captura de pantalla 2024-04-26 105637](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/assets/88221675/e43b5376-f8ec-4624-a20f-daabdcfad556)

**Comment by emguepo** [comment] 2024-04-28 19:50
well, i found the solution... only download this other file... 
![Captura de pantalla 2024-04-28 143739](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/assets/88221675/89cc8e37-c454-491b-8323-7b07daf715bc)
![Captura de pantalla 2024-04-28 143855](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/assets/88221675/7070d2ee-705a-46b7-8984-a42f33c8ca83)

**Comment by emguepo** [comment] 2024-04-28 19:50
> ![image](https://private-user-images.githubusercontent.com/160106110/304979393-4c38359b-0a23-485a-937a-aeea2b15ccea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzMzM2MzMsIm5iZiI6MTcxNDMzMzMzMywicGF0aCI6Ii8xNjAxMDYxMTAvMzA0OTc5MzkzLTRjMzgzNTliLTBhMjMtNDg1YS05MzdhLWFlZWEyYjE1Y2NlYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyOFQxOTQyMTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMzZhZGYwNjA0NDQyODIxNjM2OGJlMmU0ODk3ODQ4OGI2MmIxMGVhYTJiMDhhMTQ3NzgxNTViYTliYjA0OWUzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.RzLKQAoPytkJfIVYDiezRNJBlwsmh8l-ShQ4VLjwtvI) Hi, im getting this error, any sugestions?

see my post...

**Comment by sarvenn** [comment] 2024-04-29 04:48
> well, i found the solution... only download this other file... ![Captura de pantalla 2024-04-28 143739](https://private-user-images.githubusercontent.com/88221675/326289651-89cc8e37-c454-491b-8323-7b07daf715bc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzNjYyNTgsIm5iZiI6MTcxNDM2NTk1OCwicGF0aCI6Ii84ODIyMTY3NS8zMjYyODk2NTEtODljYzhlMzctYzQ1NC00OTFiLTgzMjMtN2IwN2RhZjcxNWJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI5VDA0NDU1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZiYTk1NjYwNGM3MDU3OThkYTZkNmEyM2QzMjc2ZDU4YTQwYzc3M2EzYmU4Mjg5Yzg5NDUyNGIyOTJmNjQ0NGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2VqHrYzkbSAgMlxWIegBaYhqHtt6RS7Kl-vQoNIZ5DQ) ![Captura de pantalla 2024-04-28 143855](https://private-user-images.githubusercontent.com/88221675/326289658-7070d2ee-705a-46b7-8984-a42f33c8ca83.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzNjYyNTgsIm5iZiI6MTcxNDM2NTk1OCwicGF0aCI6Ii84ODIyMTY3NS8zMjYyODk2NTgtNzA3MGQyZWUtNzA1YS00NmI3LTg5ODQtYTQyZjMzYzhjYTgzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI5VDA0NDU1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE4NDExNjE3NTRmZmU1NWUzZWZkY2I3YzY1NGM2YTcwZDZhYTJiN2Y1MDc3MWE4NWIwZTY2ODRiMDU0NzU5ZDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bf0J1PUSRpQZp4oplu4OO6K6W9lx_0k0iGRCyRx8nxY)

You can move that .py file to your PrusaSlicer folder (where prusaslicer.exe exists) and just  put biqu_convert_p24.py wording into post prosessing script section in your slicer.

**Comment by emguepo** [comment] 2024-04-29 14:18
In PS show this error... 
![Captura de pantalla 2024-04-29 091811](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/assets/88221675/739213f1-27f2-4cd2-9b9b-42e3881e0d11)
