### ISSUE TITLE
[BUG] Problem with the Printing.sys file

### ISSUE THREAD

**Issue by radek8** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1720] opened 2021-03-11 19:14 UTC
You still cannot confirm the pop-up asking if you want to continue printing after the interruption.
The screen freezes when clicked

![image](https://user-images.githubusercontent.com/46979052/110841496-3c226080-82a6-11eb-9b74-fde02049ca03.png)

**Comment by kisslorand** [comment] 2021-03-11 20:00
What was the cause of the interruption?

**Comment by radek8** [comment] 2021-03-11 20:15
Stornovaný tisk, ale to není důležité.
Na tlačítko se vygeruje soubor Printing.sys s infornmací kde byl tisk přerušen. Po zvolení nového tisku, vyskočení dotazu chcete pokračovat v přerušeném tisku.
Po kliknutí na kterékoli tlačítko displej zamrzne.

**Comment by kisslorand** [comment] 2021-03-11 20:17
Huh?

**Comment by radek8** [comment] 2021-03-11 20:37
The Printing.sys file is generated if the feature is enabled
Power Loss Recovery

**Comment by kisslorand** [comment] 2021-03-11 20:41
Can you show the content of the Printing.sys file? @digant73 is on this bug.

**Comment by radek8** [comment] 2021-03-11 20:50
[Printing.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/6125893/Printing.zip)

**Comment by digant73** [comment] 2021-03-11 20:50
it happened also to me. In my case the content of the file was:
SD:/very_very_very_log_long_long_very_very_very_long_long_long_file.gcode
so more than 63 chars.
The TFT freezes without prompting the "Continue printing?" dialog

**Comment by radek8** [comment] 2021-03-11 20:57
put these two files on the card and select print
[Uploading Archive.zip…]()

**Comment by digant73** [comment] 2021-03-11 21:05
used also you files. the problem is reading the Printing.sys file. On my printer the TFT freezes on "Loading" screen.
While in your TFT the dialog box was shown but then the TFT freezes

**Comment by radek8** [comment] 2021-03-11 21:17
It didn't freeze before the translation was corrected.
https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/issues/1676
https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/pull/1680

**Comment by digant73** [comment] 2021-03-11 21:39
Ok, so it should more easy to solve the bug

**Comment by bigtreetech** [comment] 2021-03-12 03:26
fixed in #1724 .

**Closed** 2021-03-12 03:28 UTC
Labels: bug
