### ISSUE TITLE
TFT35 V3 Additional Purge Resets Board

### ISSUE THREAD

**Issue by tinbasher** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1781] opened 2021-03-30 16:49 UTC
### Description

When loading in new filament and a request is made to purge more the board resets.

### Steps to reproduce

1. Unload filament
2. Load filament
3. Purge More

**Expected behavior**
More filament is purged

**Actual behavior**
System resets

### TFT Firmware Version & Main Board Firmware details
Firmware 0.26
SKR Mini E3 V2.0

[Configuration_h.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/6230724/Configuration_h.zip)

**Comment by oldman4U** [comment] 2021-03-30 18:25
Hi tinbasher.

This is not a bug of the TFT, but has been a bug in Marlin, which has been fixed 2-3 weekly ago. So please update to the nightly build of Marlin to make your STM32 based mainboard not crash anymore.

Please close this ticket here.

Thank you

**Closed** 2021-03-30 18:52 UTC
Labels: bug
