### ISSUE TITLE
[IDEA] printing menu and echo

### ISSUE THREAD

**Issue by JediRAMA** [bigtreetech/BIGTREETECH-TouchScreenFirmware#362] opened 2020-03-05 21:38 UTC
Hello. 
Any chance to change printing menu? Im using command every lyer M117 to see the end timer of printing job. And i see alltime this at my screen
![1](https://user-images.githubusercontent.com/61805782/76027896-7e51ed00-5f42-11ea-8d89-10e61f817e09.jpg)
![2](https://user-images.githubusercontent.com/61805782/76027900-80b44700-5f42-11ea-90d2-bc0fdddc65df.jpg)

Is it possible to add echo in printing menu like this example? And change a bit menu 

![tft printing menu](https://user-images.githubusercontent.com/61805782/76027644-0e436700-5f42-11ea-8abf-defda5091751.jpg)

**Comment by oldman4U** [comment] 2020-09-11 21:17
Hello Jedi.

Please close this ticket in case the issue is solved in the meantime.

May the force be with you

**Comment by oldman4U** [comment] 2020-10-09 05:42
Please help the community and close the ticket once you do not need it anymore. Thank you

**Closed** 2020-10-13 00:17 UTC
Labels: enhancement

**Comment by oldman4U** [comment] 2021-01-12 11:40
Hi.

Could you please check #1410 which could solve the reported feature request.

Thank you

**Comment by digant73** [comment] 2021-07-27 16:50
@oldman4u also this bug was fixed. M117 are now reported in status area and notification area as both toast and notification. Time Left is also properly handled by the PR implemented M73. So this bug can also be removed from the list
