### ISSUE TITLE
[BUG] Filament Sensor Problems

### ISSUE THREAD

**Issue by omexlu** [bigtreetech/BIGTREETECH-TouchScreenFirmware#2007] opened 2021-06-18 10:25 UTC
Hello,

I have a firmware for the TFT based on your development:
https://github.com/Dtcreation/Firmware-Molise-TFT

However, I have the problem with my "Artillery Genius" that the LED from the filament sensor is always green whether now filament is inside or not.

Is there a bug here?

Currently, the filament sensor does not work so.

PS. In the firmware of the TFT, the filament sensor is of course activated.

Thanks in advance.

**Comment by kisslorand** [comment] 2021-06-18 10:30
Where is your sensor connected to? Did it ever work? If yes, what has changed since?

**Comment by omexlu** [comment] 2021-06-18 10:32
Hello,
It is connected to the standard port (i.e. display), with the original firmware it worked, if there was no filament it was red otherwise green.

Since then, only Marlin and the TFT firmware has been updated (the one mentioned above).

**Comment by oldman4U** [comment] 2021-06-18 11:44
Why you use a 2 months old firmware instead of the one from here and why not opening a ticket there?

**Comment by omexlu** [comment] 2021-06-18 11:47
@Dtcreation 

Because the "developer" pulls his data from here and thus is based on here, I am looking for help here. He only compiles this and adapts it to his firmware.

**Comment by oldman4U** [comment] 2021-06-18 11:51
But he is 2 months behind.

So even there would be a problem in the firmware here and we fix it - you would not get it.

**Comment by oldman4U** [comment] 2021-06-18 11:53
So technically you ask for help for another software nobody uses here.

**Comment by omexlu** [comment] 2021-06-18 12:02
It is also based on your software so to speak a fork only with adaptations, so it is already the software that is used here :)

I assume that he will also soon update to the latest version, have him times pointed out.

Even if I want to use the software directly from here I do not know which and which is used for the Artillery Genius (stock screen).

**Comment by oldman4U** [comment] 2021-06-18 12:05
We don't know which adaptions he made. Maybe he made a mistake.

**Comment by omexlu** [comment] 2021-06-18 12:13
I don't know either, I'm a total newbie in this field:
https://github.com/Dtcreation/Firmware-Molise-TFT/tree/master/Copy%20to%20SD%20Card%20root%20directory%20to%20update/TFT%20STOCK

Let's see if he does something :)

**Comment by kisslorand** [comment] 2021-06-18 12:14
With this FW in this repository no one reported such issue.

**Comment by radek8** [comment] 2021-06-18 12:23
Use FW from this repository.
Look at the display circuit board, there could be a description of the MKS display version. If not specified, use the files on the MKS one by one, one will work. :-)

**Comment by omexlu** [comment] 2021-06-18 12:32
I think: MKS TFT28
An Mainboard is MKS GEN_L v1.0

**Comment by radek8** [comment] 2021-06-18 12:34
MKS TFT28 V3.0 or MKS TFT28 V4.0?

**Comment by omexlu** [comment] 2021-06-18 12:38
Don't know can't open at this point and find no Info on the web :/

**Comment by radek8** [comment] 2021-06-18 12:44
The @digant73  may advise which version of TFT Artillery  uses. He also has Artillery :-)

**Comment by kisslorand** [comment] 2021-06-18 12:53
It's tricky with Artillery. I have a ASWX1 and the display says it is v3.0.0 but I have to compile v4 for it., v3 doesn't work.

**Comment by digant73** [comment] 2021-06-18 12:54
it's a clone of MKSTFT28 v4.0.

**Comment by omexlu** [comment] 2021-06-18 12:56
OK so it is MKSTFT28 v4.0 😊
But now I so smart as before 😂

Do you guys with Artillery have also my behavior with the filament sensor, that very strange 😬

**Comment by digant73** [comment] 2021-06-18 12:59
with a stock ASX1 use the following settings for the filament sensor:
fil_runout:1
fil_runout_inverting:0
fil_noise_threshold:200 (safe value. That value depends a lot on the printer. On my printer it's OK to use even 50.

**Comment by omexlu** [comment] 2021-06-18 13:05
The problem is that the sensor does not run at all, as soon as I turn on the Genius the LED briefly turns red and then immediately jumps to green, whether now filament is in it or not does not matter :/

With the stock firmware is not, so the sensor does not seem to be broken.

Find that very strange.

**Comment by digant73** [comment] 2021-06-18 13:15
try my settings on the official BTT fw. If the problem is still there, try to invert the filament connector on the TFT (the 3 pins connector on B1)

**Comment by omexlu** [comment] 2021-06-18 13:21
The settings are already present except for the last (not relevant) one:
https://github.com/Dtcreation/Firmware-Molise-TFT/blob/master/Genius/Copy%20to%20SD%20Card%20root%20directory%20to%20update/TFT%20STOCK/config.ini

What do you mean by invert over exactly? Where should I plug it in? I can not just turn the wrong way in then the power supply etc is not correct

**Comment by digant73** [comment] 2021-06-18 13:24
try to set fil_runout_inverting:1
Eventually provide a picture of the TFT board with the connector.

**Comment by omexlu** [comment] 2021-06-18 13:28
I don't know what the option has to do with how the filament sensor works?
# Invert the logic of the sensor

This only inverts the logic so it will not work again 😊

The pin is exactly where it is on every artillery, nothing has been changed to it, the problem only exists since the firmware updates, with stock it works without problems

**Comment by digant73** [comment] 2021-06-18 13:36
are you using the official BTT fw? if not, switch to that and use the attached config.ini file just for testing 

[config.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/6677314/config.zip)

**Comment by omexlu** [comment] 2021-06-18 13:46
Die Werte, die in der veralteten INI vorhanden sind, sind genau die gleichen für meinen Drucker angepasst:
https://github.com/Dtcreation/Firmware-Molise-TFT/blob/master/Genius/Copy%20to%20SD%20Card%20root%20directory%20to%20update/TFT%20STOCK/config.ini

Ich kann nicht einfach diese Config nehmen, weil die weder angepasst noch für meine aktuelle Firmware ist.

Das macht die Probleme doch nur schlimmer.

**Comment by omexlu** [comment] 2021-06-18 13:57
But maybe you have a link to all the needed files for the Artillery Genius then I'll try to adjust that and update to the latest version, maybe that will fix the problem but I doubt it :/

**Comment by radek8** [comment] 2021-06-18 14:00
The current FW is free to download here

**Comment by omexlu** [comment] 2021-06-18 14:04
So i need the following:
- MKS_TFT28_V4.0.27.x.bin
- config.ini (adapt to my printer)
- language_en.ini
- and where i find the MKS Folder with this files? (https://github.com/Dtcreation/Firmware-Molise-TFT/tree/master/Genius/Copy%20to%20SD%20Card%20root%20directory%20to%20update/TFT%20STOCK/MKS)

**Comment by digant73** [comment] 2021-06-18 14:06
@omexlu unzip the following zip file on the root of the SD card and install the FW as usual.
Both, the bin, icons and config.ini file are installed.
After installation, verify if it works

[MKSTFT28_v4.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/6677486/MKSTFT28_v4.zip)

**Comment by omexlu** [comment] 2021-06-18 14:09
@digant73 Thanks i give a try later, is something special do define in config.ini except the size of the printer?

**Comment by digant73** [comment] 2021-06-18 14:10
only the build volume "size_max" (it is currently set for the ASX1 size_max:X300 Y300 Z400)

**Comment by omexlu** [comment] 2021-06-18 14:15
There is no language file on it?

**Comment by digant73** [comment] 2021-06-18 14:17
default language is english. So no need to load again the english language

**Comment by omexlu** [comment] 2021-06-18 14:33
I just flashed the firmware of the TFT successfully but unfortunately the problem persists that the filament sensor always shows green no matter if there is filament in it or not.

Here I think there could be an error/bug somewhere.

**Comment by kisslorand** [comment] 2021-06-18 20:53
Let's do a test.
Remove the middle pin from the runout sensor and check if the LED reacts to filament presence. In not, the sensor is broken.
If yes... I don't know ...
I had hunch that it must be some pin configuration problem.
I just checked the pinout definition back from 2020, it is not changed, it's still on pin PB1 and it is still defined as an input pin, either pull-up or pull-down, depending on the parameter "logic invert". Other than the input pin state, nothing else can make a working sensor not to sense the filament.

**Comment by omexlu** [comment] 2021-06-19 01:15
Which connector is it? The problem is that it was working on stock firmware :/

**Comment by kisslorand** [comment] 2021-06-19 08:20
Sorry, I was talking about the connector on the filament sensor.
So, remove the pin that faces forward (faces towards the front of the printer) from the filament sensor's cable connector.

**Comment by omexlu** [comment] 2021-06-19 08:24
I don't know if this will help, it worked under the stock firmware and gets power, but it doesn't work properly. LED always remains green whether filament is inside or not.

There are only 2 possibilities end,  a bug in connection with the tft firmware with this sensor or he is completely broken 🙈

I think but rather a bug because it works in the stock firmware without problems.

**Comment by kisslorand** [comment] 2021-06-19 08:38
So, if you write back original firmware, it works again?
Can you measure the voltage on that pin? If yes, does it change between 3.3V and 0V if filament is inserted and removed?

**Comment by omexlu** [comment] 2021-06-19 08:44
Yes under the original firmware it works, no filament in = red, filament in = green.

That's why I find that so strange, I get from support a new sensor but that may take some time until this is here (from China).

Unfortunately, I have no meter to measure that 😬 but Current seems to be on it.

**Comment by kisslorand** [comment] 2021-06-19 08:48
@digant73 
Do you have your filament sensor connected to your TFT?

**Comment by omexlu** [comment] 2021-06-19 08:52
For me I connected it to the TFT (standard port as shipped), so I think it's a bug in the firmware.

Whether the official current version from here or the one from Dtcreation both do not work with the sensor. The original however already.

I have also heard that in new deliveries a different sensor is installed, the new light green, the old blue when filament is inside.

**Comment by kisslorand** [comment] 2021-06-19 08:53
We all get it, you think it is a FW bug, no need to repeat it in every post of yours.

**Comment by omexlu** [comment] 2021-06-19 08:58
Sorry that I repeat myself I just want to contribute to the solution of the problem, I can currently work without sensor, but it would be nicer with of course :)

**Comment by oldman4U** [comment] 2021-06-19 10:10
The color of the led is irrelevant. The smart sensor works for me and I will test a standard sensor later today.

**Comment by omexlu** [comment] 2021-06-19 10:17
Maybe different Modells that makes issues, don't know. I tried with on and smart on tft settings.

**Comment by oldman4U** [comment] 2021-06-19 11:22
I have BTT mainboard, TFT and smart sensor in Ender3.

**Comment by kisslorand** [comment] 2021-06-19 11:49
I would love to know if the TFT is who's is blocking the sensor's signal wire. Without measurements I do not know how else it is possible to find out. I checked inside out the filament runout signal pin's configuration, couldn't find anything wrong with it.

**Comment by oldman4U** [comment] 2021-06-19 12:19
This will finally end with a "I found the problem" - and it was not the firmware.

**Comment by omexlu** [comment] 2021-06-19 13:07
Let's wait and see what Oldman's tests reveal about him.

Can hardly imagine that my sensor is already broken :/

**Comment by oldman4U** [comment] 2021-06-19 13:08
It is not the firmware. I tested the firmware from today with a standard sensor and it works like expected and the blue led on my sensor changes on/off whenever filament is present or not.

@guruathwal Before your PR has been merged I tested your PR with the BTT smart sensor and now with a standard sensor. In both cases the new stuff works great.

With the new firmware it is possible to define standard sensor or smart sensor in config.ini and also if the sensor is default on or off. In the TFT settings you can then turn the sensor on/off at any time. I'm loving it - or so.

@omexlu Please buy a new sensor and close this ticket, thank you.

**Comment by omexlu** [comment] 2021-06-19 13:17
However, it is strange that it works without problems under the stock firmware.

The lever of sensor is also not blocked when I inserted/executed filament I clearly hear the click but at the LED does not change.

The manufacturer will send me a new sensor (may take some time) and will then test again and then report whether it works or not.

I thank you in any case now for your help.

**Comment by omexlu** [comment] 2021-06-20 01:13
In a Facebook group 2 others already have the same problem, the filament sensor stays green.... Our sensors are definitely not broken.

**Comment by oldman4U** [comment] 2021-06-20 02:27
The BTT TFT firmware definitely works with both kinds of sensors on my printer using BTT mainboard and BTT TFT.

**Comment by omexlu** [comment] 2021-06-20 02:37
Maybe, but I just want to point out that already 3 people with stock mainboard/filament sensor (Artillery Genius / maybe actual batch) have the problem with the sensor and it just does not work there, that can not be a coincidence :)

Artillery has no BTT TFT and BTT Mainboard, maybe there is the problem with contabily to.

**Comment by oldman4U** [comment] 2021-06-20 06:04
This repository is about the firmware which is made for the BTT TFT displays.

**Comment by omexlu** [comment] 2021-06-20 06:16
Maybe but usualy supports it, because many Artillery machines use this firmware (thingiverse projects and also other maintenaner). 

Also mentioned in the Readme that MKS is supported even if not officially. 

MKS TFT Warning: BTT does not officially provide MKS TFT hardware support, MKS TFT is maintained by open source contributors, and BTT does not bear any risk of MKS TFT hardware using this firmware

MKS_TFT28_V3.0 and V4.0

MKS_TFT32_V1.3 and V1.4

**Comment by cedtr0nik** [comment] 2021-06-20 06:23
Hello, i have the same issue. Before updating : stock firmware motherboard and screen, filament green led, no filament red led. After updating motherboard and screen, filament green led, no filament green led...

**Comment by kisslorand** [comment] 2021-06-20 06:45
Please, any of you having problems, do the measurement I proposed.
I have an Artillery, but I have the old sensor with the blue led. It works just fine.

**Comment by omexlu** [comment] 2021-06-20 06:49
@kisslorand yes that the thing, people with the blue led don't have any issues as I heard, but they with the green led :/ very strange.

@cedtr0nik can you maybe take a measurement as described here, I can't, I don't have knowledge and tools:
https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/issues/2007#issuecomment-864376551

**Comment by kisslorand** [comment] 2021-06-20 07:51
Please test the attached FW.
[MKSTFT28.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/6681894/MKSTFT28.zip)

**Comment by omexlu** [comment] 2021-06-20 07:57
I can only test tomorrow/the day after I'm back home and will let you know then.

What exactly have they adjusted here just to know?

@cedtr0nik maybe you can test the attached file earlier as me :)

**Comment by kisslorand** [comment] 2021-06-20 08:01
I tried to guess how is the new sensor is different from the old one. I based my guess on the fact that it has now a bicolor led.

**Comment by omexlu** [comment] 2021-06-20 08:05
I or @cedtr0nik will let you know as soon as possible :)
May thanks.

**Comment by cedtr0nik** [comment] 2021-06-20 12:17
Ok so after updating screen "found oudated data" is indicated

**Comment by cedtr0nik** [comment] 2021-06-20 12:24
![Uploading 1.jpg…]()

**Comment by cedtr0nik** [comment] 2021-06-20 12:27
![Uploading 2.jpg…]()

**Comment by omexlu** [comment] 2021-06-20 12:28
The uploaded images don't work.

**Comment by cedtr0nik** [comment] 2021-06-20 13:04
After updating again with latest "BIGTREETECH-TouchScreenFirmware-Vx.x.27" for my MKS tft28, i still have the issue : no filament green led...

**Comment by cedtr0nik** [comment] 2021-06-20 13:10
i have tested "filament sensor" on KO and smart KO in screen settings

**Comment by omexlu** [comment] 2021-06-20 13:21
The fix should be on this file https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/issues/2007#issuecomment-864514284

But there you have this error message :/

**Comment by kisslorand** [comment] 2021-06-20 19:19
I am sorry guys, I uploaded a non merged version of this FW, you need to load a new config.ini fila also.
Here it is:
[config.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/6682948/config.zip)

**Comment by omexlu** [comment] 2021-06-21 02:47
@kisslorand 

I have just tested this FW, unfortunately it does not work here either, the LED is red during the update, but as soon as the firmware is completed and the printer is restarted, the LED is immediately back to green and no reaction when the filament in/out.

**Comment by kisslorand** [comment] 2021-06-21 03:59
Please rest this one too:
[MKSTFT28.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/6683940/MKSTFT28.zip)

**Comment by omexlu** [comment] 2021-06-21 04:21
@kisslorand 

Yes man this one works, no filament = LED RED, filament = LED green :)

I let this installed, I assume will be anyway in the next version included ?

**Comment by cedtr0nik** [comment] 2021-06-21 06:23
I am sorry but again the same message : "found oudated data" and "Fonts update required".
I have the THEME_The Round Miracle Menu Material theme on V.x.x.27 bigtreetech version
Thanks for help

**Comment by kisslorand** [comment] 2021-06-21 06:24
Easy fix, update the fonts again.

**Comment by omexlu** [comment] 2021-06-21 06:36
@kisslorand

**Comment by cedtr0nik** [comment] 2021-06-21 06:36
ok but how i can download plz ? (sorry for the newbie...)

**Comment by kisslorand** [comment] 2021-06-21 07:03
@omexlu 
https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/archive/refs/heads/master.zip
This is the current master in ZIP format. You can extract the fonts from this archive.

@cedtr0nik 
You can keep this version but keep in mind that the on I posted is not an official version, it  includes a PR (#2006) that is not merged into the master. The changes made for the filament sensor to work is a fix that will broke the filament sensor usage on other MKS  TFTs, it is not yet a general fix, rather it's a fix specific for your machine.
I really do not know if this fix will be in a future FW of this repository.

**Comment by cedtr0nik** [comment] 2021-06-21 07:21
update error... white screen !

**Comment by omexlu** [comment] 2021-06-21 08:32
@kisslorand

**Comment by kisslorand** [comment] 2021-06-21 09:27
> update error... white screen !

Put an empty "reset.txt" file on your SD card.

**Comment by omexlu** [comment] 2021-06-21 10:11
Please offer this bugfix also for upcoming versions, or a version separately if possible, because there are more people who have the new Genius with this LED version :)

Thank you very much :)

**Comment by kisslorand** [comment] 2021-06-21 20:03
Check PR #2018.

**Comment by omexlu** [comment] 2021-06-22 01:13
Super thanks :) Will there be this version in the future also precompiled?

**Comment by kisslorand** [comment] 2021-06-22 03:44
If the PR gets merged, then most probably yes.

**Closed** 2021-06-22 08:34 UTC
Labels: bug
