### ISSUE TITLE
[FAQ] Read me before posting a New Issue!

### ISSUE THREAD

**Issue by traffic-light** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1047] opened 2020-08-31 19:51 UTC
Dear reader,

**First of:**
Don't post any comment except a FAQ with an answer.
OR:  if something is wrong in the FAQ or an addition to what's already written.
 > I'll reply to this comment. Please remove it when I did this to keep the comment section clean

**That said:**
I made this FAQ, Frequently Asked Question, because a lot of questions are asked a lot lately.
In this FAQ I, and other users underneath, will post a question with a answer to it.
**Pleas check ALL FAQ's before posting a issue.**
# Known bugs 
All known bugs are listed in this pinned issue: https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/issues/1218
Please check this issue, after reading this readme, before posting

# Feature request
All the feature request that is already asked can be found in this pinned issue: https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/issues/1170
Please check this issue before posting a new feature request

# FAQ
> _When posting a FAQ underneath, please use the same style ;-)_

### Q: The print speed changes when I turn the rotary encoder
> Answer:  This happened because the encoder is hardwired to marlin.
> For some more details see: https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/issues/915#issuecomment-670661218 , https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/issues/680, https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/issues/757

### Q: Switching to Marlin mode is giving me a empty screen
>Answer: First, check your ribbon cable connections to the TFT screen.
>
>A: In case your TFT does not have an EXP connector at all (TFT28 for example), you can not use the Marlin emulator mode.
>
> B: In case your mainboard provides EXP1 and EXP2, you have to connect 2 ribbon cables connecting EXP1 and EXP2 of the mainboard to EXP1 and EXP2 of the TFT. In the Marlin firmware of your mainboard, make sure that ONLY the "REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER" is activated in Configuration.h and that all other controllers (especially the "CR10_STOCKDISPLAY") are **De**activated.
>
> C: In case you have a "E3" mainboard, which provides a single EXP connector, you have to connect 1 ribbon cable connecting EXP of the mainboard to EXP3 of the TFT. In the Marlin firmware of your mainboard, make sure that ONLY the "CR10_STOCKDISPLAY" is activated in Configuration.h and that all other controllers (especially the "REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER") are **De**activated.

### Q: Touchscreen doesn’t respond/ stay’s in the “Choose mode” selection
> Answer: There are 2 possible problems that can be causing this.
> a) The screen stay's in choose mode
> The screen is touching the frame where it’s mounted in.
> Create more clearance in between the touchscreen and the frame where you mounted it.
>
> b) The screen doesn't respond to any touch
> The touchscreen settings could be corrupted. The screen doesn't know at this moment how to correctly respond to a touch.
> A way to solve this:
> Place a text file **reset.txt** in the root of a SD-card and insert this in the screen
> Reset the screen.
> When the screen is booted there will be a touchscreen callibration screen. Calibrate the screen and it should be solved.

### Q: can't update the firmware of my tft35 V2.0
> Answer: there is a bug in the bootloader on your screen. You should update this.
> See this for more information and the new bootloader: https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/tree/master/TFT35_V2%20Bootloader%20fix

### Q: scrambled icons and/ or fonts after firmware update
> Answer: when you update you're firmware you always should check if there are also changes to the TFTxx folder (where xx stands for screen size). When these are new you should also upload this folder to your TFT screen.
> When updating the firmware it's always a good idea to update your config.ini. this will prevent unexpected behaviour.

### Q: Filament sensor triggers with filament when filament is inserted
> Answer: When you connect the filament-sensor to the TFT screen and you’ve got the message “No filament” on you’re screen it could be that you need to invert the filament sensor. To do this you should got to Menu –> Settings –> feature and search for invert filament sensor. Toggle this one. It should be solved and be working correctly

### Q: Unexpected freezes when entering a menu after newly compiled firmware
> Answer: Did you also update the config.ini on you're screen after the update? For example the freezing in preheat menu is caused by using a old config.ini.
> Please try if this work. When it didn't work place an issue and tell that you did update config.ini ;-)

### Q: I received the error “Fade height off". What does it mean and what to do?
> Answer: Fade height is a setting for auto bed level. This message will appear when you configured auto bed levelling on your printer.
>The reason you receive this message is because you didn’t setup the fade height. Fade height is made too smoothen the bed level mesh. 
>Set this to 1 or higher to get rid of this error

### Q: How to preview 3D-models on the TFT-screen
> Answer: For previewing the 3D model on the TFT screen there are some things you should do:
> 1. Install the Cura plugin: https://github.com/bigtreetech/Bigtree3DPlugin
>     --> Please read the readme on this github page!
> 2. Transfer the generated gcode to your sd-card or pendrive.
> 3. Make sure that the file-list settings is set to false in the feature menu
> 4. insert your sd-card or pendrive
> 5. In the print menu you can see the 3Dpreview for your gcode:
>     ![image](https://user-images.githubusercontent.com/37051137/93017604-523ab700-f5ca-11ea-8119-2be705b7d227.png)
>     When printing it's displayed on the bottom half of the screen.
>
> Note: To use this option you need the newest version of the TFT firmware!

### _Manual_
I'm currently working on a manual. I will put information in there about GIT, compiling/ building and more.
I try to make it easy to read with no too much text. (I hope you can appreciate it ;-) )
I've added the same FAQ in there too.
You can find it here: https://github.com/traffic-light/manual_nogoodnameyet/blob/master/EN_manual.pdf
It's not done yet. In the next version chapter 1 will be completed.

**Comment by oldman4U** [comment] 2020-09-03 05:18
@bigtreetech Thank you for pinning this ticket. Could you please move it to the first position, or even better, remove the two other pinned tickets. This is the only one which needs a prominent placement!
THANK YOU

**Comment by oldman4U** [comment] 2020-09-07 16:07
Hi.

Could you please add the following to the second Q:
Using an "E3" based mainboard, make sure that ONLY the "CR10_STOCKDISPLAY" is activated in Configuration.h. For all other mainboards, ONLY the REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER" has to be activated.

Thank you

**Comment by traffic-light** [comment] 2020-09-07 16:51
> Hi.
> 
> Could you please add the following to the second Q:
> Using an "E3" based mainboard, make sure that ONLY the "CR10_STOCKDISPLAY" is activated in Configuration.h. For all other mainboards, ONLY the REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER" has to be activated.
> 
> Thank you

Done. Thank you for the suggestion!

**Comment by oldman4U** [comment] 2020-09-07 17:14
;-) Good teamwork!

Regarding Touchscreen doesn’t respond/ stay’s in the “Choose mode” selection.

The problem with this issue is, that there is not a single issue which is caused by the shortage, but many different issues. So i would probably change it to something less specific, like: If you see issue which are not reproducible, or you have UFO's in your garden, then....

;-)

**Comment by traffic-light** [comment] 2020-09-07 17:48
> ;-) Good teamwork!
> 
> Regarding Touchscreen doesn’t respond/ stay’s in the “Choose mode” selection.
> 
> The problem with this issue is, that there is not a single issue which is caused by the shortage, but many different issues. So i would probably change it to something less specific, like: If you see issue which are not reproducible, or you have UFO's in your garden, then....
> 
> ;-)

Yes. I'll have to take a look at that later ;-)
Thank you

**Comment by oldman4U** [comment] 2020-09-23 08:04
Hi.

Hope you are doing good.

Maybe you want to adjust this part:

First, check your ribbon cable connections to the TFT screen.

A: In case your TFT does not have an EXP connector at all (TFT28 for example), you can not use the Marlin emulator mode.

B: In case your mainboard provides EXP1 and EXP2, you have to connect 2 ribbon cables connecting EXP1 and EXP2 of the mainboard to EXP1 and EXP2 of the TFT. In the Marlin firmware of your mainboard, make sure that ONLY the "REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER" is activated in Configuration.h and that all other controllers (especially the "CR10_STOCKDISPLAY") are DEactivated.

C: In case you have a "E3" mainboard, which provides a single EXP connector, you have to connect 1 ribbon cable connecting EXP of the mainboard to EXP3 of the TFT. In the Marlin firmware of your mainboard, make sure that ONLY the "CR10_STOCKDISPLAY" is activated in Configuration.h and that all other controllers (especially the "REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER") are DEactivated.

In case this problem occurs when first booting in Marlin mode, you should try rotating the encoder wheel. This way Marlin is forced to redraw the screen.

**Comment by traffic-light** [comment] 2020-09-23 20:49
> Hi.
> 
> Hope you are doing good.
> 
> Maybe you want to adjust this part:
> 
> First, check your ribbon cable connections to the TFT screen.
> 
> A: In case your TFT does not have an EXP connector at all (TFT28 for example), you can not use the Marlin emulator mode.
> 
> B: In case your mainboard provides EXP1 and EXP2, you have to connect 2 ribbon cables connecting EXP1 and EXP2 of the mainboard to EXP1 and EXP2 of the TFT. In the Marlin firmware of your mainboard, make sure that ONLY the "REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER" is activated in Configuration.h and that all other controllers (especially the "CR10_STOCKDISPLAY") are DEactivated.
> 
> C: In case you have a "E3" mainboard, which provides a single EXP connector, you have to connect 1 ribbon cable connecting EXP of the mainboard to EXP3 of the TFT. In the Marlin firmware of your mainboard, make sure that ONLY the "CR10_STOCKDISPLAY" is activated in Configuration.h and that all other controllers (especially the "REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER") are DEactivated.
> 
> In case this problem occurs when first booting in Marlin mode, you should try rotating the encoder wheel. This way Marlin is forced to redraw the screen.

I'll change it to that. Please don't remove your comment

**Comment by traffic-light** [comment] 2020-10-07 21:06
> Hi.
> 
> Hope you are doing good.
> 
> Maybe you want to adjust this part:
> 
> First, check your ribbon cable connections to the TFT screen.
> 
> A: In case your TFT does not have an EXP connector at all (TFT28 for example), you can not use the Marlin emulator mode.
> 
> B: In case your mainboard provides EXP1 and EXP2, you have to connect 2 ribbon cables connecting EXP1 and EXP2 of the mainboard to EXP1 and EXP2 of the TFT. In the Marlin firmware of your mainboard, make sure that ONLY the "REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER" is activated in Configuration.h and that all other controllers (especially the "CR10_STOCKDISPLAY") are DEactivated.
> 
> C: In case you have a "E3" mainboard, which provides a single EXP connector, you have to connect 1 ribbon cable connecting EXP of the mainboard to EXP3 of the TFT. In the Marlin firmware of your mainboard, make sure that ONLY the "CR10_STOCKDISPLAY" is activated in Configuration.h and that all other controllers (especially the "REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER") are DEactivated.
> 
> In case this problem occurs when first booting in Marlin mode, you should try rotating the encoder wheel. This way Marlin is forced to redraw the screen.

Done. Can you check if you agree?

By the way, I'm currently too busy for the manual. When i have time, again. i'll change from word to LaTeX.

That's easier to maintain when more users are making changes to it

**Comment by oldman4U** [comment] 2020-10-07 21:14
Perfect. But you have some awnser instead of answer. Let me know if you need help somewhere.

**Comment by traffic-light** [comment] 2020-10-07 21:16
haha. i'm sorry.. I've got to sleep i think...

**Comment by traffic-light** [comment] 2020-10-29 08:26
Motion for me:
* Remove the word faq in post
* Make section with known bugs
* Make section with faq
* Add "printer not connected" to the faq (check cables, serial ports and correct orientation of black ribbon cable)
*

**Comment by oldman4U** [comment] 2020-10-29 08:33
I would make an extra ticket with known bugs where verified bugs are collected. The Bot will start closing unused tickets very soon.

**Comment by traffic-light** [comment] 2020-10-29 09:07
In my opinion it's better to have 1 location that you should read first. ;-)

Outlook for Android<https://aka.ms/ghei36> downloaden
________________________________

**Comment by oldman4U** [comment] 2020-10-29 09:13
I agree. But the read me first should probably include information like where to look for known issues and already reported fr. How to start a new ticket. How to behave and when to close a ticket. More general stuff. And then 2 others with FRs and bugs. 

My 2c

**Comment by oldman4U** [comment] 2020-11-27 14:11
THANK YOU BTT!!!

@traffic-light Could you please change the title of this ticket to Read me before posting a New Issue! It is now right above the "New Issue" button and I hope people understand the relation between the two things;-)

**Comment by bigtreetech** [comment] 2020-11-27 14:13
@oldman4U done!

**Comment by oldman4U** [comment] 2020-11-27 14:17
;-)

Thank you, even you are not my friend from the Netherlands;-)))

**Comment by traffic-light** [comment] 2020-11-27 14:28
@oldman4U  placed a link to your pinned issues in the maintext

**Comment by oldman4U** [comment] 2020-11-27 14:40
Cool, thank you!

Seems we got some great structure, hope users will use it;-)

**Closed** 2020-11-28 19:40 UTC
Labels: bug

**Comment by radek8** [comment] 2020-12-09 21:12
> 
> ### Q: The print speed changes when I turn the rotary encoder
> > Answer:  This happened because the encoder is hardwired to marlin.
> > For some more details see: [#915 (comment)](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/issues/915#issuecomment-670661218) , #680, #757
> 

@traffic-light Please correct the error description.

Guruathwal has created a fix to address this issue.
the condition is a new FW Marlin and connection via connectors EXP1 and EXP2
For connection via EXP3, adjustment does not work.

I have an idea how to apply Guruathwal correction also for deskz with EXP3 connector (for example SKR mini E3).
It means a small modification of Marlin and the connection of one wire.

**Comment by traffic-light** [comment] 2020-12-09 22:24
> > ### Q: The print speed changes when I turn the rotary encoder
> > > Answer:  This happened because the encoder is hardwired to marlin.
> > > For some more details see: [#915 (comment)](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/issues/915#issuecomment-670661218) , #680, #757
> 
> @traffic-light Please correct the error description.
> 
> Guruathwal has created a fix to address this issue.
> the condition is a new FW Marlin and connection via connectors EXP1 and EXP2
> For connection via EXP3, adjustment does not work.
> 
> I have an idea how to apply Guruathwal correction also for deskz with EXP3 connector (for example SKR mini E3).
> It means a small modification of Marlin and the connection of one wire.

Thank you for notifying me. Forgot it there was a fix for 2 wired marlin mode.

Wil update it soon

**Comment by oldman4U** [comment] 2021-01-02 08:14
Hi Peter.

Hope you are good!

The link https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/tree/master/TFT35_V2%20Bootloader%20fix does not work anymore.

**Comment by traffic-light** [comment] 2022-01-20 22:10
> https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/tree/master/Bootloaders/TFT35_V2%20Bootloader%20fix

thanks. fixing it
