### ISSUE TITLE
[BUG] Gcode Filename letter followed by number shows ???? when printing from Onboard SD

### ISSUE THREAD

**Issue by blueeagle69** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1158] opened 2020-10-06 22:53 UTC
Hi.

I've noticed a weird issue when browsing GCode on my onboard SD card.
I think it's fine when files are on TFT media.
On some files, the names show as "????"
![20201006_234538](https://user-images.githubusercontent.com/9963876/95268262-e0533780-082e-11eb-8f80-bb6640f8f008.jpg)

The file name shows as B1SENS~1.GCO when I select it.
The long filename is "B1 sensor_bracketWIP V3_1_0.2mm_PLA_29m.gcode".
The filename is a tad long, but the question marks are weird.

I do wish the TFT would support long filenames when printing from onboard media.

**Comment by zonalimitatore** [comment] 2020-10-07 01:06
maybe dont like .GCO
Try rename to .GCODE

**Comment by blueeagle69** [comment] 2020-10-07 14:07
It has a .GCODE extensuin, but the TFT shortens filenames when printing from the Onboard SD  😒 All the rest are fine, but I always seem to get one that shows "????"

**Comment by zonalimitatore** [comment] 2020-10-07 14:17
Try to rename it,more short and without any point or symbol

**Comment by blueeagle69** [comment] 2020-10-07 14:18
Was about to try the same thing. Will  let you know

**Comment by blueeagle69** [comment] 2020-10-07 14:23
Nope I shortened the filename right down.
I also removed all underscores although the rest have them.

It still shows as "????"

**Comment by zonalimitatore** [comment] 2020-10-07 14:32
there is again 0.2 in filename?

**Comment by blueeagle69** [comment] 2020-10-07 14:32
Okay then.

I shortened the filename to B1 Sensor Bracket.gcode.
Same thing.
I then removed the B1 and left it as Sensor Bracket.
That worked.
I then put it back minus the space after B1, it came back as ???? on the TFT.
I then put the B back and left out the "1". It worked.
So for some reason the TFT doesn't like a number after the first character of the filename?

**Comment by zonalimitatore** [comment] 2020-10-07 14:36
Ahahahahahaha.....omg
One day...one bug

**Comment by blueeagle69** [comment] 2020-10-07 14:37
Confirmed. I created a dummy Gcode file and called it A3 Test.gcode.
It showed as ???? on the TFT.
I think I may have stumbled across a bug.
Only in TFT

**Comment by zonalimitatore** [comment] 2020-10-07 14:41
Ive name this without problem.....Now i try like you do

![Annotazione 2020-10-07 163936](https://user-images.githubusercontent.com/43097238/95346244-e6432a00-08bb-11eb-8ea4-71bb7df41d1f.jpg)

**Comment by blueeagle69** [comment] 2020-10-07 14:44
Yeah that would work. It just doesn't like a number after the first character for some reason.

**Comment by zonalimitatore** [comment] 2020-10-07 14:48
My work😯
![IMG_20201007_164550](https://user-images.githubusercontent.com/43097238/95347185-e98ae580-08bc-11eb-9674-1e1e6aee751c.jpg)

**Comment by blueeagle69** [comment] 2020-10-07 14:49
I just tested again. The bug is limited to onboard SD printing 😔

**Comment by zonalimitatore** [comment] 2020-10-07 14:53
🙈🙈🙈🙈🙈

**Comment by zonalimitatore** [comment] 2020-10-08 08:48
Dude,change the label in BUG.It's confirmed

**Comment by zonalimitatore** [comment] 2020-10-08 14:02
I mean delete QUESTION and set like BUG😉

**Comment by blueeagle69** [comment] 2020-10-08 14:12
> I mean delete QUESTION and set like BUG😉

Apologies, lol.
I changed the {Q] label to [BUG] immediately, but for some reason the tag hasn't updated.
But it definitely shows [BUG] in the title.

**Comment by blueeagle69** [comment] 2020-10-08 14:17
I suppose I could close this one and start a nee bug report and mention this one?

**Comment by oldman4U** [comment] 2020-10-08 16:23
Not sure, because so far you the only one having this problem. I just tested it and can not reproduce it on my machine. Do you want to test the attached code file?

[C3_Dusche Mitnehmer.gcode.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/5349351/C3_Dusche.Mitnehmer.gcode.zip)

I am able to see the right name when I try to print it from the SD card which is interred into the mainboards card reader.

Let me know

**Comment by radek8** [comment] 2020-10-08 19:39
How old is the FW in the display? This problem was resolved some six months ago.

**Comment by oldman4U** [comment] 2020-10-08 20:04
Am I remember right, that there was such an issue before... Unfortunately Git does not allow to search for "?", at least it shows no result even I can see it on the first page;-)

**Comment by blueeagle69** [comment] 2020-10-08 20:10
> Not sure, because so far you the only one having this problem. I just tested it and can not reproduce it on my machine. Do you want to test the attached code file?
> 
> [C3_Dusche Mitnehmer.gcode.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/5349351/C3_Dusche.Mitnehmer.gcode.zip)
> 
> I am able to see the right name when I try to print it from the SD card which is inserted into the mainboards card reader.
> 
> Let me know

I just tried your gcode on my onboard SD.
It shows as "????" on screen.

**Comment by oldman4U** [comment] 2020-10-08 20:22
From when is your firmware?

**Comment by blueeagle69** [comment] 2020-10-08 20:57
Helloo again 😀
It's a pretty recent build I downloaded a little over a week ago.
The last commit was #1060

**Comment by blueeagle69** [comment] 2020-10-08 22:31
> How old is the FW in the display? This problem was resolved some six months ago.

It was a recent build, but I just downloaded the latest master again just for the hell of it.
Same issue when listing files from onboard media.
Any file with a number directly after the first character displays as ????. If I click it, it shows me the 8.3 filename.
(Long filenames from onboard media would ne nice).
Any file uploaded to TFT media displays as expected.
Also Marlin mode is unaffected.

**Comment by oldman4U** [comment] 2020-10-09 04:56
Which Marlin? I use v2.0.7 official release. And do we know your mainboard?

**Comment by oldman4U** [comment] 2020-10-09 09:58
And WHY did you change the picture??

**Comment by blueeagle69** [comment] 2020-10-10 00:05
Apologies for the delay in getting back to you.
I was bored so thought I would mess about with my profile image!
My Marlin version is 2.061
And my board is a SKR 1.4

**Comment by blueeagle69** [comment] 2020-10-10 00:20
I didn't actually realise 2.0.7 was released.
Downloading now 😀

**Comment by blueeagle69** [comment] 2020-10-10 01:10
Amazingly since updating to Marlin 2.0.7 the issue has gone.
Filenames that were showing as ???? before now show as normal.
Annoyingly though Gcode stored on the onboard SD still revert to 8.3 when selected.

**Comment by oldman4U** [comment] 2020-10-10 04:26
What a wonderful start into the day👍🏻

**Comment by oldman4U** [comment] 2020-10-10 04:35
Time to close this ticket 😁

**Comment by blueeagle69** [comment] 2020-10-10 23:58
😀

**Comment by blueeagle69** [comment] 2020-10-11 23:06
Well that's annoying and bizarre.
I just updated the printer to Marlin 2.0.7.1 and the ???? thing has returned 😣

**Comment by oldman4U** [comment] 2020-10-12 22:52
But this problem is obviously coming from Marlin. You should open a ticket there.

**Comment by blueeagle69** [comment] 2020-10-13 00:39
I was thinking the same thing sometime after posting.
Will close (again)

**Closed** 2020-10-13 00:46 UTC
Labels: question

**Comment by oldman4U** [comment] 2020-10-13 04:52
And you know how to reopen it😁

Strange that only you can see this. Maybe it is a setting!??

**Comment by blueeagle69** [comment] 2020-10-13 21:09
🤣
Yeah personally I think my 3D printer is trying to drive me to the asylum.
I think for now I will simply remember not to name my files in a way that causes the blasted ???? 😉
All the best!

**Comment by oldman4U** [comment] 2020-10-13 21:15
Maybe a good decision. 👍🏻

**Comment by oldman4U** [comment] 2021-01-31 16:00
Verified on my printer using current Marlin and TFT fw, so I added it to the verified Bugs list.

**Comment by blueeagle69** [comment] 2021-01-31 22:34
Thank you 😀

**Comment by guruathwal** [comment] 2021-03-08 16:15
what's the status of this bug with reference to the latest commit? does it still exist?

**Comment by oldman4U** [comment] 2021-03-08 16:56
Was there end of Jan so I guess yes. Will verify and let you know asap.

**Comment by oldman4U** [comment] 2021-03-08 17:10
[M75 Lorem ipsum dolor sit amet.gcode.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/6102999/M75.Lorem.ipsum.dolor.sit.amet.gcode.zip)

Hi. Please unzip and try to print from bSD On Board SD card slot. The absolutely same card (microSd to SD card adapter) shows the names correctly when trying to print from TFT SD card slot.

**Comment by oldman4U** [comment] 2021-03-09 14:40
Hi. Could you please check PR#1699 which likely solves the problem.

Thank you

**Comment by oldman4U** [comment] 2021-03-09 20:17
Hi birdy;-)

Could you please check Gurmeet's PR to see if it fixes the reported issue: https://github.com/guruathwal/BIGTREETECH-TouchScreenFirmware.git

Thank you

**Comment by oldman4U** [comment] 2021-03-10 08:02
Thank you Gurmeet. Verified that it works so I remove the issue from the Verified Bugs list.
