### ISSUE TITLE
[FR] Change icon

### ISSUE THREAD

**Issue by DrumClock** [bigtreetech/BIGTREETECH-TouchScreenFirmware#869] opened 2020-07-25 18:52 UTC
### I would suggest changing the icons in  `"Babystep"` modes.

**I would replace the original**  

![Inc](https://user-images.githubusercontent.com/64655979/88464112-7c200900-ceb8-11ea-9179-715bafe00e3c.jpg)
![Dec](https://user-images.githubusercontent.com/64655979/88464115-7e826300-ceb8-11ea-82ee-2c54577c8555.jpg)

 **with   "NOZZLE"  icons**

![Nozzle -](https://user-images.githubusercontent.com/64655979/88464127-90640600-ceb8-11ea-8c36-04ad064939ba.jpg)
![Nozzle +](https://user-images.githubusercontent.com/64655979/88464128-922dc980-ceb8-11ea-9a7a-07bff1625730.jpg)

**Comment by bryan065** [comment] 2020-07-26 06:45
Icons can probably be changed as part of #863 as well?

**Comment by DrumClock** [comment] 2020-07-26 09:16
**How to change icons?**
I downloaded the current version for TFT 50 V3.0 compiled in VSC and the` .bin `file updated the display.

**Comment by Tygrys-1** [comment] 2020-07-26 15:40
Make a folder on SD card called TFT50. Copy there the content of the "Copy to SD Card root directory to update....."\TFT50 folder, change the icons you have in the zip with corresponding ones in this folder and boot the printer with the SD in the TFT slot.

**Comment by DrumClock** [comment] 2020-07-26 16:27
Hi, 
Okay, but it replaces the icons in all menus where there are "+/-"

**I just want to replace it in the "Babystep" menu.**
Is there no need to change something directly in the FW TFT50?

![Babystep_menu](https://user-images.githubusercontent.com/64655979/88484265-97008500-cf6d-11ea-93ef-18c5b64fb00a.jpg)

**Comment by Tygrys-1** [comment] 2020-07-26 18:41
For this you'll have to modify the firmware. You have to add the icons using unique names to the icon list and to the icon folder, and modify the menus to display your icons. The icon space is limited and I do not know, if we can add new ones or how many of them. This is to be checked.

**Comment by DrumClock** [comment] 2020-07-26 19:09
### I am not a programmer, can you please check it and add it if necessary? 
If it could, could this be added as well?

![save babystep Z offset](https://user-images.githubusercontent.com/64655979/88487311-40eb0c00-cf84-11ea-867f-8d923b732702.jpg)

### I would replace and test the modified files.
Thank you

**Comment by Tygrys-1** [comment] 2020-07-26 19:29
Sorry to say, I'm not that skilled to do this.

**Comment by DrumClock** [comment] 2020-07-26 19:46
### OK, maybe someone will contact me who can handle it :)

**Comment by bryan065** [comment] 2020-07-26 23:56
Hey @DrumClock, I've added an optional `#define FRIENDLY_PROBE_OFFSET_LANGUAGE` TO #863. You'll be able to use it once it gets merged

**Comment by DrumClock** [comment] 2020-07-27 05:16
Hey @bryan065 
in the `"Z Offset"` menu? I meant in the `"BabyStep"` menu.
**If I now change the value in the "Z Offset" menu, the Hotbed does not move.** 
However, if I do it via the "BabyStep" menu, it can be seen immediately.

**Comment by DrumClock** [comment] 2020-07-27 06:32
I have tried your FW `pr/1` for TFT50 and it looks very nice. 
**At UBL, I would just warm up HotBed to 70 degrees first.**

I use two HotEnd on V-extruders and a Touch MI probe.
https://www.youtube.com/watch?v=BOaIMiyzaks
https://www.youtube.com/watch?v=DsCdpfjLS2g

I quite miss the TFT menu from the LCD 12864.
Could it be added to the configuration?
![config](https://user-images.githubusercontent.com/64655979/88510472-580d1680-cfe3-11ea-85dd-ff5b4e19dedd.jpg) 
### TOOL OFFSET
![tool offset](https://user-images.githubusercontent.com/64655979/88510487-5fccbb00-cfe3-11ea-9608-3554922af70c.jpg)
### TOUCHMI
![Touch Mi](https://user-images.githubusercontent.com/64655979/88510500-665b3280-cfe3-11ea-8b9b-f8b77999da4f.jpg)

**Comment by radek8** [comment] 2020-07-27 21:39
I agree to return the sabe offer in the Baby-step offer.
It was originally there and someone removed it

**Comment by DrumClock** [comment] 2020-07-28 06:18
Hi, @radek8 
The **Z Offset** value is saved, but the value does not change in the BabyStep menu.
After pressing the reset the icons will be overwritten incorrectly  ....**. it's confusing ....**

**Comment by radek8** [comment] 2020-07-28 06:27
That is right
The Z Offset value is saved. Baby Step is added or subtracted from Z Offset
Baby Step always starts at zero

**Comment by DrumClock** [comment] 2020-07-28 06:50
@radek8 
### That's not good ... it's confusing.

![start](https://user-images.githubusercontent.com/64655979/88629243-498c3100-d0af-11ea-9f4c-37ccb8447548.jpg)
![change](https://user-images.githubusercontent.com/64655979/88629248-4bee8b00-d0af-11ea-9698-6b293743e40b.jpg)
![reset](https://user-images.githubusercontent.com/64655979/88629260-501aa880-d0af-11ea-8b5e-2f68fb955bfe.jpg)

**Comment by radek8** [comment] 2020-07-28 07:24
That's not good. :-(
I'll try to fine-tune it in the evening

**Comment by radek8** [comment] 2020-07-28 08:22
The fact that the Z Offset is not saved could also be caused by the old version of Marlin.
How old is your version of Marlin?

**Comment by DrumClock** [comment] 2020-07-28 09:29
**Marlin-bugfix-2.0.x  /  Downloaded: 16.7.2020**

**Comment by DrumClock** [comment] 2020-07-28 15:22
Hi @radek8 
Once you've started it, you should finish it.  :)
It looks like Digant73 will release its update right away. :(

**Comment by radek8** [comment] 2020-07-28 21:51
> Hi @radek8
> Once you've started it, you should finish it. :)
> It looks like Digant73 will release its update right away. :(

@DrumClock
I added a Save button to the BabyStep menu.
Can you try it?
#878

**Comment by DrumClock** [comment] 2020-07-29 05:59
> @DrumClock
> I added a Save button to the BabyStep menu.
> Can you try it?
> #878

Umíte česky ?

**Comment by radek8** [comment] 2020-07-29 07:06
> > @radek8
> > I added a Save button to the BabyStep menu.
> > Can you try it?
> > #878
> 
> Umíte česky ?
Ano :-)
Yes, but the local community will not like it if we use a language other than English

**Comment by DrumClock** [comment] 2020-07-29 07:08
> > > @radek8
> > > I added a Save button to the BabyStep menu.
> > > Can you try it?
> > > #878
> > 
> > 
> > Umíte česky ?
> 
> Ano :-)
> Yes, but the local community will not like it if we use a language other than English

I understand that, can we talk Czech together somewhere?

**Comment by radek8** [comment] 2020-07-29 07:22
radek.zobalzavinacptacek.cz

**Comment by DrumClock** [comment] 2020-07-29 08:28
thanks, I have already sent an e-mail .... did not come?

**Comment by DrumClock** [comment] 2020-07-30 10:21
> Hey @DrumClock, I've added an optional `#define FRIENDLY_PROBE_OFFSET_LANGUAGE` to #863. You'll be able to use it once it gets merged
> 
> ![zoffset2](https://user-images.githubusercontent.com/30362590/88492641-2744c700-cf7a-11ea-8636-2a5306dbbfd9.jpeg)

### Hi @bryan065 
**branch `pr/1` means flawless.**
I would just add Hotbed heating for ABL.

**Closed** 2020-08-01 10:03 UTC
Labels: enhancement
