### ISSUE TITLE
[BUG] babystep in touchscreen mode

### ISSUE THREAD

**Issue by BsCmOD** [bigtreetech/BIGTREETECH-TouchScreenFirmware#943] opened 2020-08-08 21:26 UTC
Hi, I want to report a just discovered issue. Since I compiled and update (the day before yesterday) my TFT35V3 (connected to a SKR1.4 turbo with the very last Marlin bugfix version) to 26.x version, babystep function it's no available during printing in touchscreen mode (however I can see the thumbnail of my gcode file) with the old version (V26) it was available also during this procedure. Have you got any idea to how to solve this issue? Just another thing, BTT had annunciated the 27 firmware version for their screens some time ago (about 2 o 3 weeks ago) but it was never released, the question is why? Thank'you for support

P.S. Also the M117 message in gcode file it's not visualized as popup with smart popup activated function.

**Comment by radek8** [comment] 2020-08-08 22:15
Will be fixed #940

**Comment by BsCmOD** [comment] 2020-08-08 22:36
> 
> 
> > babystep function it's no available during printing in touchscreen mode
> 
> Will be fixed #940

Thank's man, any prevision?

**Comment by digant73** [comment] 2020-08-09 09:08
@BsCmOD the M117 popup message was removed (currently is simply commented out in the code) because too much verbose in many cases (e.g. it was displayed at each layer change). However, the message is displayed in the status bar

**Comment by BsCmOD** [comment] 2020-08-09 10:11
> @BsCmOD the M117 popup message was removed (currently it is simply commented out in the code) because too much verbose in many cases (e.g. it was displayed at each layer change). However, the message is displayed in the status bar

OH, ok, in fact in many cases was noisy anyway if it's used in smart mode it will visualized just for a few seconds a time. In status bar I can't see anything just the file name. Is there any options to enabled into menu extra?

**Comment by digant73** [comment] 2020-08-09 11:14
@BsCmOD probably in a next PR the M117 smart notification will be displayed.
The problem is that what is good for someone is not good for others

**Comment by BsCmOD** [comment] 2020-08-09 11:34
> @BsCmOD probably in a next PR the M117 smart notification will be displayed.
> The problem is that what is good for someone is not good for others

Yes, absolutely, for that function it could be possible add another options into the menu to turn on or off

**Closed** 2020-08-10 09:33 UTC
Labels: bug
