### ISSUE TITLE
[BUG] Print information screen disappears after the end of a print

### ISSUE THREAD

**Issue by fftkatarn** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1316] opened 2020-11-30 13:40 UTC
### Description

After the last upgrade, the print information screen automatically exits after the end of a print instead of being persistent.
I'm not sure if it was intentional but there should be the possibility to choose the behavior.

### Steps to reproduce

1. Start a print
2. In the end there are two "beeps" and the information screen (where print time, temperature, flow etc can be seen) automatically exits.

**Expected behavior**

Like in the old firmware, there should be the possibility to manually exit the information screen with a "back" or "exit" button.

**Actual behavior**

The information screen exits as soon as the print ends.

### Hardware Variant

TFT35 E3 v3.0

### TFT Firmware Version & Main Board Firmware details

TFT35_E3_V3.0.26.x Nov 27 2020

Marlin 2.0.7.2

**Comment by oldman4U** [comment] 2020-11-30 17:03
Hi.

Would you please verify that the reported issue does NOT exist in case you are printing from on board sd card, but exists when printing from TFT uDisk and TFT SD card.

Thank you

**Comment by fftkatarn** [comment] 2020-11-30 20:55
Hello,
Unfortunately I can't verify since I just realized that when I try to print from the on-board sd card, the TFT gives me an empty error dialog..

**Comment by oldman4U** [comment] 2020-11-30 21:34
Select the TFT sd card or udisk first before you select the on board sd card.

**Comment by fftkatarn** [comment] 2020-11-30 21:38
Unfortunately that didn't work, I still have the attached error together with a noisy continuous beep.

![photo_2020-11-30_22-36-48](https://user-images.githubusercontent.com/30617177/100668749-b3b62a80-335c-11eb-9104-aefd7409a393.jpg)

**Comment by oldman4U** [comment] 2020-11-30 21:43
Ok. Thank you no problem. I have all information and let you know asap.

👍🏻

**Comment by fftkatarn** [comment] 2020-11-30 21:45
Thank you very much!

**Comment by GregSKR** [comment] 2020-12-01 08:41
Hi
This is caused by PR https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/pull/1272 wich introduce lot af bugs...
Here is the faulty code (in green):
![Menu_Printing](https://user-images.githubusercontent.com/58402797/100716588-2f45c500-33b9-11eb-8217-cde67d53b4ca.png)

**Comment by oldman4U** [comment] 2020-12-02 09:03
Finally it is more a feature than a bug, but a option would be great. Finally a better handling of a finished print would be great.

@fftkatarn Do you need anything for now?

**Comment by fftkatarn** [comment] 2020-12-02 09:54
Ok, for me it's important to have an option because after every print I take note of the print time on the display, so I need to see it somehow.
Thank you!

**Comment by oldman4U** [comment] 2020-12-02 11:43
Understand.

In this case I would recommend to stay with a firmware which has been generated right before the PR has been merged, until a new functionality has been added, like this one: https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/tree/68615eceaf531ad659826820bb8e9b19dc38f199

I assume you are printing from the on board SD card, right?

**Comment by fftkatarn** [comment] 2020-12-02 11:47
Nope, I can't print from the onboard SD since the TFT returns me the error in the screenshot above (is this a bug? Should I open another issue about that?).
Anyway I always printed from the on-screen SD card.
Thank you

**Comment by oldman4U** [comment] 2020-12-02 12:29
This ticket is about exiting after print. In case you have another issue, I would recommend to open another ticket.

Using the same TFT I can not see the error above, but issues accessing the on board SD card where there is already a PR available for this. Printing from TFT based storage has been working with all versions of firmware I have been testing the last couple of days. So you can open a new ticket or you can wait for the on board SD card fix to be merged and see if this solves your 2nd problem.

Happy printing

**Comment by oldman4U** [comment] 2020-12-02 12:40
You are very welcome!

IF YOU WANT, you can try this firmware, which has hopefully all storage related issues fixed: https://github.com/kisslorand/BIGTREETECH-TFT/tree/ONBOARD_SD-Hangs

**Comment by mpcolman** [comment] 2020-12-02 16:50
Im always print from the TFT SD card slot, the issue exist there too... no print info when finished printing-----

**Comment by oldman4U** [comment] 2020-12-02 19:52
Printing from TFT there is no information. Printing from on board sd there was such an information which included the elapsed time, but this seems to be gone.

**Comment by oldman4U** [comment] 2020-12-03 16:02
Please check #1333 which shows a Print finished screen independent of the used storage.

**Comment by fftkatarn** [comment] 2020-12-03 16:10
> Printing from TFT there is no information. Printing from on board sd there was such an information which included the elapsed time, but this seems to be gone.

Maybe there was a misunderstanding, I always printed from the TFT SD (never from the on-board SD) and the post-print information was always there.

> Please check #1333 which shows a Print finished screen independent of the used storage.

That's good, I personally prefer the good ol' screen if possible to have it back though!

**Comment by oldman4U** [comment] 2020-12-03 16:15
I do not know this good old screen but maybe you want to give it a try and report issues if you find one.

**Comment by fftkatarn** [comment] 2020-12-03 16:33
That's exactly the purpose of this issue..

> ### Description
> After the last upgrade, the print information screen automatically exits after the end of a print instead of being persistent.
> I'm not sure if it was intentional but there should be the possibility to choose the behavior.

I try to explain myself better.
Step 1: I start a print from the TFT SD card reader, the display shows me a screen with the temperature, fan, flow and time elapsed information;
Step 2: The print ends: in the old firmware the information screen in step 1 remains there, in the new one no, it exits automatically.

What I'm asking is if it is possible to restore the old behavior.

Thanks!

**Comment by oldman4U** [comment] 2020-12-03 20:24
You mean the landing screen. I would call it a bug that you had to stop the print after the print was done. What was the benefit of having this information persistent and that you had to stop the print at the end of the print?

**Comment by fftkatarn** [comment] 2020-12-03 20:57
The benefit was the fact that I could take note of the print time, for me it wasn't a bug but a useful thing.
It would be nice to have an option in the config.ini file to choose to make it persistent or not.

**Comment by oldman4U** [comment] 2020-12-03 21:05
Makes sense. The new method shows not only the elapsed time but also the amount of filament used in case this information is available. Check the PR and let me know.

**Comment by fftkatarn** [comment] 2020-12-04 12:50
> IF YOU WANT, you can try this firmware, which has hopefully all storage related issues fixed: https://github.com/kisslorand/BIGTREETECH-TFT/tree/ONBOARD_SD-Hangs

I tried that firmware but no popup showed at the end of the print printing from the TFT SD reader, still not working the print from onboard SD.

**Comment by fftkatarn** [comment] 2020-12-04 12:52
That's the screen I'd like to have back. It was not a bug, it was useful and always worked.

![photo_2020-12-04_13-19-51](https://user-images.githubusercontent.com/30617177/101165935-c28c2e00-3637-11eb-9883-487070b0dfb5.jpg)

**Comment by oldman4U** [comment] 2020-12-04 20:22
Hi.

And this is what you get with the new firmware. Elapsed time and Filament used.

![IMG_7466](https://user-images.githubusercontent.com/54359396/101210906-92b04b00-3676-11eb-8b1f-4f47df1602ce.jpg)

In addition the print does not stutter, the Layer hight is shown correctly, there is no useless Pause button and you do not have to stop a print which has already finished.

Hope you enjoy it

**Comment by fftkatarn** [comment] 2020-12-04 21:12
I never stopped an already finished print, what are you talking about?
The popup it's ok but in the firmware you told me to try it didn't work for me.

**Comment by oldman4U** [comment] 2020-12-04 21:24
Depending on the firmware version, the storage device which has been used for the print, and if the print has been canceled before the print started or once the print has been going on or if the print has finished - different landing screens have been used and sometimes there was a print finished dialog and sometimes not. It was a mess. In addition some landing screens had still a Stop button, even the print has finished already. We unified this so now there is always a print finished screen which includes the elapsed time and in case available also the amount of filament used.

This is available in a PR which will hopefully be available soon in the master firmware and which can be downloaded from this private repo: https://github.com/mehmetsutas/BIGTREETECH-TouchScreenFirmware

Please let me know

**Comment by fftkatarn** [comment] 2020-12-04 21:33
available in a PR which will hopefully be available soon in the master firmware and which can be downloaded from this private repo: https://github.com/mehmetsutas/BIGTREETECH-TouchScreenFirmware
> 
> Please let me know
Just tried but no popup..

**Comment by oldman4U** [comment] 2020-12-04 21:35
Have you self compiled the firmware?

**Comment by fftkatarn** [comment] 2020-12-04 21:36
Nope, I used the pre-compiled firmware

**Comment by oldman4U** [comment] 2020-12-04 21:55
Thats the problem.

Can you compile your own?

**Comment by oldman4U** [comment] 2020-12-11 12:02
Hi.

All changes are in the master branch. Without the Print finished popup screen activated, you should get your classic landing screen.

Please install, verify and let us know or close this ticket in case the print screen stays like expected.

Thank you

**Comment by fftkatarn** [comment] 2020-12-11 19:58
Hi, sorry for the late reply, I was quite busy and I didn't have time to compile and test the suggested version in the last days.
I just tried the pre-compiled version in the master branch and it works! Now when a print finishes, the print screen is persistent and I have to press "back" to exit.
Thank you very much, you made me happy :)

**Closed** 2020-12-11 19:59 UTC
Labels: bug

**Comment by oldman4U** [comment] 2020-12-11 21:53
👍🏻

fftkatarn <notifications@github.com> schrieb am Fr. 11. Dez. 2020 um 20:58:
