### ISSUE TITLE
Blobs / Zits on print when serial connected (SKR Mini E3 1.2 + BTT TFT Screen + Octoprint)

### ISSUE THREAD

**Issue by robstermn** [bigtreetech/BIGTREETECH-TouchScreenFirmware#388] opened 2020-03-13 04:02 UTC
I am having this issue as well, with SKR Mini E3 1.2 + BTT TFT Screen V35 + Octoprint.
Printing from Octoprint, I get these small zits all over.
I've increased the baudrate from 115200 to 250000 with the same issue.

![76570689-e2fdd200-6483-11ea-9467-4cb94c84b452](https://user-images.githubusercontent.com/9891262/76588543-481deb80-64b5-11ea-95a6-dc1f29def56b.png)

![76570748-032d9100-6484-11ea-8c81-d22c595295cd](https://user-images.githubusercontent.com/9891262/76588556-4fdd9000-64b5-11ea-91fd-e79a546891ae.png)

If I print from the TFT display via micro SD, prints fine???

![76570994-82bb6000-6484-11ea-852d-b95c496efae3](https://user-images.githubusercontent.com/9891262/76588574-5bc95200-64b5-11ea-802c-77c990612ee2.png)

![76571077-a8e10000-6484-11ea-828f-4029c43c0f2c](https://user-images.githubusercontent.com/9891262/76588611-64ba2380-64b5-11ea-97b3-86b0957a9d0d.png)

**Comment by guruathwal** [comment] 2020-03-13 05:50
Duplicate of #282 
this was fixed in MarlinFirmware bugfix-2.0.x https://github.com/MarlinFirmware/Marlin/pull/17032
you need to update your Marlin firmware to the latest bugfix version.

**Comment by JWolfJr** [comment] 2020-03-13 07:07
I'm running the latest bug fix and still having the stuttering and blobs. I also have my octopi connected to the TFT from the gpio pins to uart3. Changed my baud rate to 250000, also enabled rapid communication. Is there anything I forgot?

**Comment by RohanClegg** [comment] 2020-03-13 14:09
Having the same issue. Please fix. Also, on the touch screen i don't have the ability to pause or adjust anything whilst octoprint is printing.

**Comment by robstermn-64** [comment] 2020-03-13 14:35
I'm using the latest Marlin from:
[https://github.com/morningreis/Marlin-SKR-E3-Mini-1.2](url)

And I've tried both versions with the same result pictured above.

Here are my configs for reference:

[https://drive.google.com/open?id=1d3piwB5Yty5qhABel1vJHKe91o0p0F_q](url)

**Comment by guruathwal** [comment] 2020-03-14 07:42
@robstermn-64 The Marlin firmware you are using is not the latest version.
 you need to get it from here: https://github.com/MarlinFirmware/Marlin/tree/bugfix-2.0.x

**Comment by guruathwal** [comment] 2020-03-14 07:44
Also, Marlin 2.0.5 was just released 2 hours ago. https://github.com/MarlinFirmware/Marlin/releases/tag/2.0.5

**Comment by CRCinAU** [comment] 2020-03-20 06:51
Close the report... Use the right firmware and it'll go away...

**Comment by JWolfJr** [comment] 2020-03-20 07:56
I'm using the latest, it's definitely better. Only print so far still leaving blobs and zits is when I printed a lithophane. Both TFT modes. Otherwise no problems. If I ever decide to do more lithophanes, I'll just use the SD card. Thank you to all for the hard work.

**Comment by bjoernwedi** [comment] 2020-03-21 18:35
It is no marlin bug: had the same when printing over onboard printer sd.
Seems in marlin Mode the rx buffer is not read, so marlin get‘s Stück and flushes After a while, the continues. If you increase Marlins serial buffers it gets better, but at high speeds the issue Returns.
I would Renommees to read the marlin buffer frequently to ensure it does not exhaust.
This also explain, while there is no issue when printing from lcd sd, because them serial is used in Touch Mode, so buffer is read anyways.

**Comment by bjoernwedi** [comment] 2020-03-21 18:37
> Close the report... Use the right firmware and it'll go away...

On. It depends on your print Speed. When printing at 90mm/s or abviere, the issue returns

**Comment by bjoernwedi** [comment] 2020-03-21 18:39
For Proving the issue: If you use marlin Mode and print from onboard and (Printer Mainboard) while the Black serial tft cable is connected, you will See at Some speed the blobs starting.
Do not stop the print, just remove the Black serial cable and no stuttering/blobs will Appell anymore.

**Comment by JWolfJr** [comment] 2020-03-22 13:50
Nevermind, tried printing from a thumb drive and the TFT/printer locked up as soon as I tapped on the gcode file.  I know I've seen an open issue about this, but I can't find it.

**Comment by jidayME** [comment] 2020-03-30 08:57
SKR Mini E3 TFT 24, the same issue. If shown main screen I have zits. If I turn another menu than everything fine.

**Comment by manuamador** [comment] 2020-07-12 09:52
Same here, with previous Marlin and latest Marlin. Printing from onboard SD card is ok. With octoprint, zits and blobs.
Something is wrong with either the board firmware (from BTT) or the TFT firmware or both.

**Comment by CRCinAU** [comment] 2020-07-12 14:22
You haven't updated to the latest Marlin 2.x.x version.... Do that and the problem will be fixed.

**Comment by manuamador** [comment] 2020-07-12 16:30
I have the latest Marlin from this GitHub. My Pi is connected to the board. Should I Try to connect it to the screen ?
I may try without the tft screen. It sends commands that cause halts during the print.

**Comment by Tomthi** [comment] 2020-07-22 17:40
I'm seeing the same thing on a SKR 1.4 with a TFT24. When I print from Octo it see the most artifacts on curves, there is a slight hesitation on curves. The only way to get around this is to either disconnect the TFT in Touch screen mode, print off the SD card on the TFT or  print to Octo and switch to emulation mode. I've tried a bunch of stuff but this seem to be the only workaround.

**Closed** 2020-08-19 03:31 UTC
Labels: bug
