### ISSUE TITLE
[FR] Home button in the corner leveling menu

### ISSUE THREAD

**Issue by radek8** [bigtreetech/BIGTREETECH-TouchScreenFirmware#2855] opened 2023-10-05 10:52 UTC
I'm missing the Home button in the corner leveling menu.
If I move the screws, the center of the bed also moves, and I would like to execute the G28 command again.
If the M48 button were moved elsewhere, there would be a free position.
The M48 button is not important when leveling corners. 
The M48 button is already in the BL-Touch menu.

What do you think about replacing the M48 button with a Home button?

**Comment by kisslorand** [comment] 2023-10-05 11:32
What do you think what would be a better option? To home all axes or only Z?

**Comment by radek8** [comment] 2023-10-05 12:50
Both options are possible, but you can only choose one :-)
For most users, only the Z axis would probably be enough.
My opinion is that the G28 Z would be enough.
Corner leveling doesn't take long to time out the stepper motors.

**Comment by radek8** [comment] 2023-10-05 12:56
Could a condition be used?
If the stepper motors hold, will G28 be executed Z if the motors do not hold, will G28 be executed?
The display probably has no way of detecting whether the stepper motors are active.

**Comment by kisslorand** [comment] 2023-10-05 13:19
The ideal situation would by entering into this menu to disable Y steppers idle timeout and when exiting from this menu to restore original idle timeout value. Unfortunately there is no way to enquire the idle timeout value set up in Marlin.
Your reasoning about using `G28 Z` seems valid to me. 
I was also thinking about making that button to home only Z when pressed short and home XYZ when pressed long. The problem is that users most probably would be unaware of the long press function of that button.
Another solution could be to replace "Distance" with "Next" and that button to rotate the function of the "Home" button between "Distance", "Home All" and "Home Z".

What do you think?

**Comment by radek8** [comment] 2023-10-05 13:40
Switching parameters with the Next button is useless.
I would set the G28 z.
If someone wants Home for all axes, they can clean up the parameter and recompile.
If he can't do it, I'll be happy to help him with it if he asks :-)

**Comment by kisslorand** [comment] 2023-10-05 13:48
How does this look?

![L corner_0](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/assets/50251547/974e616c-f81f-4db2-9e0e-5f9006bc72b7)

**Comment by radek8** [comment] 2023-10-05 14:43
Nice

**Comment by sarvenn** [comment] 2023-10-05 15:15
This is only required for printers that uses a probe for Z homing, right?

**Comment by kisslorand** [comment] 2023-10-05 15:24
The whole menu is useful only for printers that use a probe for Z homing.

**Comment by digant73** [comment] 2023-10-05 16:03
it should be better a submenu as done in other menus (e.g. `Manual Leveling` menu)

**Comment by kisslorand** [comment] 2023-10-05 16:10
> it should be better a submenu as done in other menus (e.g. `Manual Leveling` menu)

Hmmmm, I was just about to propose the removal of the submenu in the manual leveling menu because in my opinion "DisarmXY" has no practical use there.

Original:   
![Leveling_0](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/assets/50251547/0e83746d-4335-4ae1-9798-a58d0a89e816)

Proposed:
![Leveling_1](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/assets/50251547/5061a205-f2eb-4f9f-9285-3943e5c681ca)

**Comment by kisslorand** [comment] 2023-10-06 10:49
PR #2825 is updated now with the discussed changes.

**Comment by digant73** [comment] 2023-10-06 16:30
basically the opposite of #2633 and what users ask for

**Comment by kisslorand** [comment] 2023-10-06 18:23
Sorry, I do not understand. What is exactly what users are  asking for that is implemented in https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/pull/2633 and taken away in #2825?

**Comment by digant73** [comment] 2023-10-07 11:02
> > basically the opposite of #2633 and what users ask for
> 
> Sorry, I do not understand. What is exactly what users are asking for that is implemented in #2633 and taken away in #2825?

People asks for integrating new/missing settings not to replace a feature with his preferred one. In #2825 you removed two functions (one in LevelCorner and one in Leveling). The unlock function in Leveling is useful for a fast/initial setup of the bed (moving the nozzle all around the bed) before fine tuning with knobs and eventually with LevelCorner (for printers with a probe). I also use it
Don't forget to re-enable the ban!

**Comment by rondlh** [comment] 2023-10-07 13:53
> Don't forget to re-enable the ban!

LOL! Don't worry, fools will be fools :D

**Comment by kisslorand** [comment] 2023-10-07 18:33
> People asks for integrating new/missing settings not to replace a feature with his preferred one. In https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/pull/2825 you removed two functions (one in LevelCorner and one in Leveling). The unlock function in Leveling is useful for a fast/initial setup of the bed (moving the nozzle all around the bed) before fine tuning with knobs and eventually with LevelCorner (for printers with a probe). I also use it

Understood, thank for the clarifications. 
You think people need to know the standard deviation of their probe before doing the corner leveling and they need to enter into the manual leveling menu to be able to do the "moving the nozzle all around the bed" by hand, which is a very stupid thing to do, it can fry the motherboard.
BTW, I heard you have a new puppy, do not forget to pet him. He seems to be so happy barking at people you dislike, all he needs in return just approval and some attention from you.
<br>

> Don't forget to re-enable the ban!

No need, there's an automated troll detection activated.
<br>

> LOL! Don't worry, fools will be fools :D

\- Sparky! Where's the bad man?!
\-  Wufff! Wufff!"
<br>

******************************************************

Note to people in their right mind: __PLEASE DO NOT__ activate the stepper motors by hand! It can be fatal for the motherboard. I know it the hard way.

**Comment by digant73** [comment] 2023-10-08 10:51
It's up to you to provide another PR difficult to be merged. The request from radek8 was lawful and involving a specific menu very easy to be satisfied. FR received a suggestion from what you consider an enemy and then you put your effort on changing something your enemy referred to instead of what has been requested by this FR adding/justifying your changes with your usual non sense words or bug reports. I usually provide/ed support to all users requesting help, clarification and support for improving the project. You were also one of them before you started to manifest your attitude cutting by yourself the bridge with all the rest of the team even banning people here and there. I'm not sorry you are ridiculing yourself, to say at least, I'm sorry you put more effort on providing spites in the project most of the time. Here, simply another example

**Comment by kisslorand** [comment] 2023-10-08 12:22
Most certainly you have the right to your own opinion.

I will not lower myself to your level and call you names, anyone around here mature enough can see what's there to see.

As a side note, thank you very much for the free publicity, bringing the attention towards me will help more and more people to  try the alternative FW from [my repository](https://github.com/kisslorand/BTT-TFT-FW) and the result of the work I've done there would be the truth, not what random trolls are mumbling on the internet. The only thing people care about is to have finished prints done as perfectly as possible. [The proof is in the pudding.](https://www.dictionary.com/e/slang/the-proof-is-in-the-pudding/)

**Comment by rondlh** [comment] 2023-10-08 17:55
@kisslorand Nobody cares about your buggy and slow repository, you must be out of your mind to even consider it. Your code is of very poor quality, because you do not communicate, coordinate, test or do peer reviews. Of course the outcome cannot be taken seriously. Your false performance claims have been debunked over and over again. **Don't forget to re-enable the ban!**

**Comment by kisslorand** [comment] 2023-10-08 18:14
Most certainly you have the right to your own opinion.

I will not lower myself to your level and call you names, anyone around here mature enough can see what's there to see.

As a side note, thank you very much for the free publicity, bringing the attention towards me will help more and more people to try the alternative FW from [my repository](https://github.com/kisslorand/BTT-TFT-FW) and the result of the work I've done there would be the truth, not what random trolls are mumbling on the internet. The only thing people care about is to have finished prints done as perfectly as possible. [The proof is in the pudding.](https://www.dictionary.com/e/slang/the-proof-is-in-the-pudding/)

**Closed** 2024-01-15 02:08 UTC
Labels: enhancement
