### ISSUE TITLE
[Question] TFT35 V3.0 - Wifi (ESP01S) implementation

### ISSUE THREAD

**Issue by Patag** [bigtreetech/BIGTREETECH-TouchScreenFirmware#113] opened 2019-11-06 18:23 UTC
Is there any functional code for ESP01S module when plugged in the dedicated LCD connector ?
If yes, where can I find documentation/tutorial on set-up ?
Thanks.
BTW, the new Unified theme is great ! Bravo !

**Comment by carl1961** [comment] 2019-11-06 20:36
works with pronterface, https://github.com/luc-github/ESP3D

**Comment by Patag** [comment] 2019-11-07 10:28
Ok, thanks. I already did that.
But I'm trying to set up a SKRPro 1.1 / TFT35 v3/ ESP01S config. I'm currently able to get wifi when module is plugged on SKR but in this case TFT is no more usable (serial port used by ESP). So I'm trying to make ESP functional when plugged in TFT. It looks like ESP doesn't even boot in this config. Any idea ?

**Comment by guruathwal** [comment] 2019-11-08 02:46
Try a simple blink sketch from arduino ide on the esp then plug it in the display and check if it is working or not

**Comment by kordris** [comment] 2019-11-08 17:33
I would also like some more info on this, I gotten the a sketch loaded from Adruino setup on the module, then had it seen on my wifi and even set it up. before I even turned it off. I pluged it on the back of the tft display. I don't have it picking up on my wifi either. So is there anything need to be done on the tft display or what. There is no kinda documentation on this. Come on you guess need to give some more info on how this should be handled.

**Comment by Patag** [comment] 2019-11-08 18:18
Exactly same issue here.

**Comment by Aleks-MO** [comment] 2019-11-08 18:23
https://www.facebook.com/groups/505736576548648/permalink/768393890282914/

**Comment by huczas** [comment] 2019-11-08 18:26
@Aleks-MO 
https://www.facebook.com/groups/505736576548648/permalink/768393890282914/
Can you write here what’s there those who don’t have a Facebook account?

**Comment by Aleks-MO** [comment] 2019-11-08 18:32
https://scontent-arn2-1.xx.fbcdn.net/v/t1.15752-9/71550618_1276625229191403_5913931428403347456_n.jpg?_nc_cat=111&_nc_oc=AQl3q11lQLTYGlxBsnBl9I1yoQxStFXW9IP3CYerGAnnp7iGEFQUKzETWntifn75DoE&_nc_ht=scontent-arn2-1.xx&oh=46b2b291cdcfd94a9002542f48b8c490&oe=5E44CF77
Flip pins for TFT35 v3.0
https://scontent-lga3-1.xx.fbcdn.net/v/t1.0-9/71293326_136541530997653_8271056587649449984_n.jpg?_nc_cat=108&_nc_oc=AQnaAjUi974iAOXKbqp7eC48K3px_rQUZCy832ZGnu-qH4jhMgQAt0hwAScPQ7Te4a4&_nc_ht=scontent-lga3-1.xx&oh=a3dc1f4dfc777068731c4e7d2a9c220d&oe=5E55F559

Set as here.
https://scontent-lga3-1.xx.fbcdn.net/v/t1.0-9/70966260_137029790948827_2585636416033652736_n.jpg?_nc_cat=111&_nc_oc=AQmT2YkOeRq21l_liHMSl2AYsiSAYLCP-WuPMWWDqNM8fn17-_Qb5W4ZkOxIJ7nDgEA&_nc_ht=scontent-lga3-1.xx&oh=74eaa71156cd3818af9f9d5ac840ff3c&oe=5E54D20F

**Comment by guruathwal** [comment] 2019-11-08 18:33
if it was working before connecting to the board then you should check if there is +5V on "ch_pd" pin of ESP after adding it to the board and turn it on.

**Comment by huczas** [comment] 2019-11-08 18:45
As I understand that fist photo "flip pins on esp01" it's completely wrong in comparison with a official pinout
https://github.com/bigtreetech/BIGTREETECH-TFT35-V3.0/blob/master/BIGTREETECH%20TFT35%20V3.0/Hardware/TFT35%20V3.0-PIN.pdf

**Comment by kordris** [comment] 2019-11-08 18:54
Is there anything on the marlin software side that we need to update to get this working?

**Comment by Aleks-MO** [comment] 2019-11-08 19:26
@huczas Tak, zrozumieli poprawnie, zdjęcie połączenia COM-TTL3.3v i instalację programu do programowania ESP. Sam BIN znajduje się w folderze https://github.com/bigtreetech/BIGTREETECH-SKR-PRO-V1.1/tree/master/firmware/esp-01s       Przepraszamy za automatyczne tłumaczenie..)))

**Comment by Aleks-MO** [comment] 2019-11-08 19:31
![WP_20190925_12_15_09_Pro](https://user-images.githubusercontent.com/22274265/68504965-dfa4d080-026e-11ea-9908-553fa3db82df.jpg)
Tak powinno być.    
![WebESP](https://user-images.githubusercontent.com/22274265/68505080-1975d700-026f-11ea-9fa3-e5e133a6635c.jpg)

**Comment by huczas** [comment] 2019-11-08 21:50
@Aleks-MO thanks that translation was pretty much ok 😉 lets stay with English.
After burning that bin file on all of my 3 esp01's all of them are showing same in serial:
```
 ets Jan  8 2013,rst cause:4, boot mode:(3,4)

wdt reset
load 0x4010f000, len 1384, room 16
tail 8
chksum 0x2d
csum 0x2d
v8b899c12
~ld
```
This is my setup for flashing:

![](https://4.bp.blogspot.com/-V8TR5ykekA4/VvChEEQk34I/AAAAAAAAAeI/L0RsQvxg7lMFmma1RIqN9hBnmeCFmT3Gw/s1600/ESP-01_Connection_Diagram_Rev.A2.PNG)

![Obrazek](https://user-images.githubusercontent.com/17404598/68512942-0d434700-027a-11ea-8f16-183e9537b498.jpeg)

Do you have any hint?

**Comment by Aleks-MO** [comment] 2019-11-08 22:33
https://sprut.ai/client/blog/950  
Description, it is necessary so. Better without buttons. [https://sprut.ai/static/media/cache/00/00/70/40/950/33117/3000x_image.jpg?1552119510](url)

Firmware program
https://youtu.be/wYaJr2cYFnc?t=162

bin address 
![000](https://user-images.githubusercontent.com/22274265/68515037-4a163a80-0288-11ea-975c-12352f3c55d8.jpg)
Everything should work out.

**Comment by Aleks-MO** [comment] 2019-11-08 22:46
After the firmware, ESP became an access point! When connecting for the first time, the address is 192,168,0,1 
Default Configuration
Default Settings:

Access Point: ESP3D
PW:12345678
Authentification: WPA
IP: 192.168.0.1
Baud rate: 115200
Web port:80
Data port: 8888
if Authentication is enabled :
User: admin
Password: admin
User:user
Password: user


Description here.
https://github.com/luc-github/ESP3D

**Comment by Sthopeless** [comment] 2019-11-09 09:30
Is not possible to implement the TFT's flashing the ESP3D bin file from the sdcard to the ESP01?! 
This would help a lot of users, I am seeing every now and then a post on facebook asking how to flash the esp01's with esp3d

**Comment by guruathwal** [comment] 2019-11-09 10:13
the Pins on TFT do not match with Pins of ESP
![Untitled-1](https://user-images.githubusercontent.com/22422544/68526946-47a6f580-0307-11ea-893e-b23af7f43aa9.png)

**Comment by Aleks-MO** [comment] 2019-11-09 10:19
@Sthopeless  NO!

**Comment by guruathwal** [comment] 2019-11-09 10:24
> ![WP_20190925_12_15_09_Pro](https://user-images.githubusercontent.com/22274265/68504965-dfa4d080-026e-11ea-9908-553fa3db82df.jpg)
> Tak powinno być.
> ![WebESP](https://user-images.githubusercontent.com/22274265/68505080-1975d700-026f-11ea-9fa3-e5e133a6635c.jpg)

Fliping the ESP will leave the EN / CH_PD pin of esp on NC pin of the TFT. EN / CH_PD needs to be pulled up with 3v for the ESP to work.

**Comment by Aleks-MO** [comment] 2019-11-09 10:31
did not understand your question. BTT just do not stand on the side of the board put the plug, "inside out."

**Comment by carl1961** [comment] 2019-11-09 11:59
As you see in the picture the pins need to be heated up with a soldering iron and shoved through to the other side of the board

**Comment by guruathwal** [comment] 2019-11-09 14:01
> did not understand your question. BTT just do not stand on the side of the board put the plug, "inside out."

a question and a doubt: the ESP is seen working in the pictures above when it is flipped, but then the EN (Enable) pin of the esp connect to the NC (no connection : not connected to any thing) pin on the boards as it is labeled on the board schematics. The EN pin of the ESP need to be connected to 3v for it to work. then how is it working if it is not connected to anything?

**Comment by Patag** [comment] 2019-11-09 14:05
I confirm this pin-out, at least for power supply. Did not apply it as is but with Dupont wires (to stay compatible with my USB adapter/programmer). This ESP module out of the box fits for SKR Pro but needs flip for TFT.

**Comment by Aleks-MO** [comment] 2019-11-09 15:07
@guruathwal  
Everything works and is very good. You just have to try.

**Comment by kordris** [comment] 2019-11-09 15:25
Ok, I got mine working with jumper wires since it's not same as the board. But is there any info on how to update the info on getting the printer info. I can pull up some info but it's not really letting do anything. Its pulling some data under the printer tab.

**Comment by guruathwal** [comment] 2019-11-09 15:45
@Aleks-MO  I have TFT35 V2.

**Comment by Hukuma1** [comment] 2019-11-12 17:41
The confusion is the newest version (TFT35 V3) with the wifi module finally works as intended... just plug it in and it powers on. Prior versions you had to fix by soldering I believe.

**Comment by Patag** [comment] 2019-11-12 19:43
Newest ? Since what date ? I've a TFT35 V3 and need to flip esp01s connector. Is there as V3.x ? ATM, I can't find any confusion !

**Comment by Hukuma1** [comment] 2019-11-12 19:48
![wifihere](https://user-images.githubusercontent.com/54511555/68705064-457cab00-0542-11ea-8fec-e37631787065.png)

I received it about 3 weeks ago. Ordered from Aliexpress. E3 v1.2 along with wifi module. Different wifi module?

**Comment by Aleks-MO** [comment] 2019-11-12 21:24
@Hukuma1 Show me the work.

**Comment by Sthopeless** [comment] 2019-11-12 21:30
my v3.0 also works with the esp01

**Comment by Hukuma1** [comment] 2019-11-12 21:37
![uglywifi](https://user-images.githubusercontent.com/54511555/68712768-41a45500-0551-11ea-9842-35e17658eb8c.jpg)

Ignoring the ugly popup UI, it does work. Although does your wifi module stop working when you issue a M503 command, @Sthopeless? I can issue it, it reports back the info, but then ceases to accept anymore commands unless I reset the TFT. Wondering if bug?

**Comment by Sthopeless** [comment] 2019-11-12 21:48
Sorry I didn't test any further, I saw it connected and that was it as I dont use esp3d. I check now what is flashed on the esp01 atm or if is not esp3d i will test M503 tomorrow

**Comment by guruathwal** [comment] 2019-11-13 03:16
If @Hukuma1 have the same display as others. Then it might be just mislabeled pins.

**Comment by Patag** [comment] 2019-11-13 10:04
![IMG_0884](https://user-images.githubusercontent.com/48475891/68753216-ee8bda00-0604-11ea-89db-d0849a0a5e5a.jpg)
![IMG_0883](https://user-images.githubusercontent.com/48475891/68753233-f481bb00-0604-11ea-8f27-4af068ba56ec.jpg)

Esp connector label is different here.
What is your version (as seen on first picture) ?

**Comment by huczas** [comment] 2019-11-15 12:14
In my version the label is "ESP" and I can confirm that it works when I just plug normal esp01. If it't upsidedown it is not powered. 

Second thing in my case is that after boot up my esp01 even if its on - is not connecting and not powering properly, it means that there is no wifi, and no any sign on screen that it's working. 
red light on esp01 is on that's it.

If I power my esp01 to FTDI to my PC and open putty I see that it is booting and showing hided ssid:ESP3D with IP:192.168.4.1 with no password.

Is there a possibility to connect ESP01 to different RX/TX connector?

**Comment by huczas** [comment] 2019-11-15 14:14
Last shot that I want to compare, @Hukuma1 can you show your configuration.h part with serial ports are configured?
In my board, when I use 12v and connect also usb my PC can't connect do the board. The only way to pass Gcode is a USB stick or SD card connected to TFT.

**Comment by marcocm** [comment] 2019-11-22 11:29
For what I have seen, there are two TFT35 V3.0.
One that has a ESP label and other that has a ESP-8266.
If you have the TFT with the ESP label, you can just connect the WIFI ESP module.
 In my case, I can connect the printer and control de printer using ESP3D. 
I just can't use the WEBUI SD options. I can't upload files .gco or .gcode and I can't see the files in the SD Card. I think I might have to update some configuration on marlin/ESP3D/Screen firmware. Also, to use the SD card do I have to connect some EXP1/EXP2/EX3 cable? I am just using the TFT cable to connect the Screen to de BBT SKR V1.3 board.

I read some where that the board and the screen worked bette with the BAUDRATE of 250000, and I tried it and I confirmed it.

**Comment by Hukuma1** [comment] 2019-11-24 22:11
Sorry for the late reply, @huczas! I am using standard Marlin 2 branch settings. This is for SKR Mini E3 v1.2 board:

'/**
 * Select the serial port on the board to use for communication with the host.
 * This allows the connection of wireless adapters (for instance) to non-default port pins.
 * Note: The first serial port (-1 or 0) will always be used by the Arduino bootloader.
 *
 * :[-1, 0, 1, 2, 3, 4, 5, 6, 7]
 */
#define SERIAL_PORT 2

/**
 * Select a secondary serial port on the board to use for communication with the host.
 * This allows the connection of wireless adapters (for instance) to non-default port pins.
 * Serial port -1 is the USB emulated serial port, if available.
 *
 * :[-1, 0, 1, 2, 3, 4, 5, 6, 7]
 */
#define SERIAL_PORT_2 -1'

**Comment by ORGATHM** [comment] 2020-01-20 15:21
> > ![WP_20190925_12_15_09_Pro](https://user-images.githubusercontent.com/22274265/68504965-dfa4d080-026e-11ea-9908-553fa3db82df.jpg)
> > Tak powinno być.
> > ![WebESP](https://user-images.githubusercontent.com/22274265/68505080-1975d700-026f-11ea-9fa3-e5e133a6635c.jpg)
> 
> Fliping the ESP will leave the EN / CH_PD pin of esp on NC pin of the TFT. EN / CH_PD needs to be pulled up with 3v for the ESP to work.

what is the name of the pronterface style wifi tool?
thanks

**Comment by Aleks-MO** [comment] 2020-01-20 16:10
**@ORGATHM** I did not understand the question. If you are talking about the look in the browser, then read here - https://github.com/luc-github/ESP3D-WEBUI

**Comment by ORGATHM** [comment] 2020-01-20 18:14
@Aleks-MO oo, sorry. i was in the webinterface with my phone but i could see this pronterface style interface.
my fault. i think i have to upload some thing into the small interface.

![Screenshot_20200120-191154_Chrome](https://user-images.githubusercontent.com/3952398/72749009-212ff100-3bb9-11ea-9e79-9682b9ab2820.jpg)

**Comment by Aleks-MO** [comment] 2020-01-20 22:13
@ ORGATHM 
Of your files marked in red, take them here  https://github.com/bigtreetech/BIGTREETECH-SKR-PRO-V1.1/tree/master/firmware/esp-01s
![ewewewe](https://user-images.githubusercontent.com/22274265/72760845-ca3f1180-3be2-11ea-9cda-49264c01612c.jpg)
![ERERETT](https://user-images.githubusercontent.com/22274265/72760880-e17dff00-3be2-11ea-8894-8aaada556b2f.jpg)

**Comment by SargFowler** [comment] 2020-01-28 12:14
Just as a thought, would I actually require a display if I just wired the ESP module up to my SKR V1.3 board serial pins? I could access the printer via the webpage.

**Comment by Aleks-MO** [comment] 2020-01-28 12:26
@SargFowler    It’s more convenient to work with him....

**Comment by Aardvarx55** [comment] 2020-02-26 16:46
Very keen to get the Wifi operational on my just installed BTT-TFT35-E3 V3.0, and although the ESP8266 is powered, it doesn't appear to boot (the blue led seem on continuously, which it doesn't when plugged into my programming rig, where it becomes visible on the network).
Noted earlier comment on board marking i.e. ESP and ESP8266, but mine is 'WIFI" (see photos).
Anyone got one of these 'WIFI' marked boards working?
![Board details](https://user-images.githubusercontent.com/42945630/75366896-5a920580-58b7-11ea-89af-75c8e9f7419e.JPG)
![WiFi socket](https://user-images.githubusercontent.com/42945630/75366936-6b427b80-58b7-11ea-8226-e5ea8335ae1d.JPG)

**Comment by ssombra** [comment] 2020-02-26 17:05
Is it possible to connect a wifi module to the TFT35 V2.0 ? It doesn't have a socket but in the manual there is a section labeled wifi with pins labeled: RX, EN, RST, 3.3V, GND, NC, NC, TX

**Comment by Aardvarx55** [comment] 2020-02-26 19:11
It's got a socket for a EAP8266, it just doesn't seem to work....
I think this is the latest board, as it has the extra board below the encoder.

**Comment by redonebe** [comment] 2020-02-29 23:23
I have the same problem. TFT 3.5 V3.0. Both LED's on the ESP keep on. I measured the board and pins EN and RST are not high so the ESP can not work.

**Comment by Aardvarx55** [comment] 2020-03-01 00:19
I've got my ESP8266 working now...
The schematic for the TFT35-E3 V3.0 shows the ch_pd pin as NC (not connected), which I believed would stop the ESP booting, as the ch_pd needs to be high.
So I connected the it via jumper cables, but connected ch_pd to VCC, and it boots whilst connected to the TFT board... result.
Having proved that it would boot, I soldered a link directly on the ESP module, and now I can insert it without the jumper cables, and it works.
I have ESP3D running on it, have it connected to my home network, and am getting responses from the printer... early days for me, as I've never used ESP3D, but my aim is to be able to upload .gcode files via WiFi (I currently print from SD card)
![image](https://user-images.githubusercontent.com/42945630/75617075-25edaa80-5b52-11ea-983e-1c32c9d514cd.png)
![image](https://user-images.githubusercontent.com/42945630/75617080-36058a00-5b52-11ea-9c63-6a535f6e512e.png)

**Comment by Scope666** [comment] 2020-03-01 02:24
I wonder if that solder mod is necessary if you're using BTT's ESP-01S board?

**Comment by Aleks-MO** [comment] 2020-03-01 08:18
@Scope666  No.

**Comment by Scope666** [comment] 2020-03-01 08:25
> @Scope666 No, you don't need anything.

Yeah, that's what I figured.  I'm guessing it's because he's using another vendor's board.

**Comment by Aleks-MO** [comment] 2020-03-01 08:40
@Scope666      
There is ESP 01 another ESP01S, they are different .... if you do not dig deep ...))

**Comment by Aardvarx55** [comment] 2020-03-01 11:14
Interesting. I hadn't realised there were two types... Anyway, that's what I have been using for other projects, so at least it's only a minor mod, and just for testing.
Thanks for the heads up.

**Comment by Aleks-MO** [comment] 2020-03-01 11:36
@Aardvarx55   
![esp8266_wiring](https://user-images.githubusercontent.com/22274265/75624890-74865d80-5bc1-11ea-9444-0f8f13647541.png)
![WP_20190925_12_26_32_Pro](https://user-images.githubusercontent.com/22274265/75624916-aeeffa80-5bc1-11ea-904c-be6561fc41bd.jpg)

**Comment by Aardvarx55** [comment] 2020-03-01 12:13
I see the schematic has CH_PD connected to VCC :o)

**Comment by redonebe** [comment] 2020-03-01 22:51
@Aardvarx55 

Best practice is to put a 10K resistor between 3,3V and CH_PD and one between 3,3V and reset. I will certainly work with a direct connection but it is safer with a 10K resistor.

This is how I did it.
![ESP - 1](https://user-images.githubusercontent.com/7701565/75635564-70852a80-5c17-11ea-841d-7ba022b6e888.jpeg)

**Comment by Aardvarx55** [comment] 2020-03-02 00:16
You are course quite right. I should have used a 10K resistor for the 'pull up' on CH_PD.
The RESET pin is addressed by the TFT board, so I haven't played with that :o)
I'm afraid I just copied what my programming rig has.
Will have to change both...
Thanks for your help, Robbie

**Comment by dineshvyas** [comment] 2020-03-02 15:54
64mbit. Enough space to play with.

**Comment by Aardvarx55** [comment] 2020-03-02 17:08
Looks like 1Mb will not be enough for ESP3D over the air updates, and probably other enhancements, so I've ordered a few 4Mb chips...
Wish me luck changing them :o)

**Comment by Scope666** [comment] 2020-03-02 17:10
I wonder what BTT's "official" ESP-01S module is shipping with ... 1MB?

**Comment by redonebe** [comment] 2020-03-02 17:12
@Aardvarx55 

Good luck. I changed already 6 Sonoff's and 4 ESP-01's. No problem at all. If you have a good look at the one i uploaded you can see the 4MB on it.

**Comment by SargFowler** [comment] 2020-03-02 20:23
![PNG image](https://user-images.githubusercontent.com/60389724/75714155-13df4980-5cc3-11ea-8d19-6c307d7b3f91.png)
Looks to be 8mbit flash.... 
But the ESP3D software fits on this ESP module OK. I have it working.

**Comment by Aardvarx55** [comment] 2020-03-03 19:51
Thanks Robert. I got my 4Mb chips today (only ordered yesterday, so very impressed).
Not having either a hot air system, or even some desoldering braid (most get some), I decided that as I didn't need to retain the 1Mb chip, that I'd simply cut the legs and remove with a solder sucker (if the iron didn't get them off).
But I obviously didn't cut well enough (or check well enough), as I pulled off one of the pads (Doh!).
Luckily, the through connection point saved me, as I soldered a short wire to what remained, and the soldered the 4Mb chip on top of the other end (plus the other pins of course).
It took be a couple of goes to get the soldering right, but I now have a 4Mb ESP01 running ESP3D, with a much healthier FS.
Thanks to all :o)

**Comment by maurobertorotta** [comment] 2020-03-26 08:26
Hello, just a question to people have WiFi up and running with web interface ... what’s about the speed of the uploading GCode to the SD ?

**Comment by Aleks-MO** [comment] 2020-03-26 09:57
No.

**Comment by maurobertorotta** [comment] 2020-03-26 11:50
> 
> 
> No.

Anyway if the problems seem to be only memory how much is needed for ESP32 -WEBUI ?
4Mb is enaugh ?
The chip SargFowler show Q80B-104HIP seems 8Mb ...

**Comment by Aleks-MO** [comment] 2020-03-26 12:26
The transfer to the SD goes through the RX TX, that's where all the speed is! And there she’s not ....

**Comment by maurobertorotta** [comment] 2020-03-26 22:23
> The transfer to the SD goes through the RX TX, that's where all the speed is! And there she’s not ....

Roughly more or less than Octoprint that use G-code Sd redirect ? This way is very very slow ...

Someone know why RepRap assure “High speed (typically 800kbytes/sec) file upload to the SD card over Ethernet or WiFi” ? 
https://reprap.org/wiki/RepRap_Firmware

If the serial is the bottleneck there are some board with Sd shared like in Toshiba Flashair ?

**Comment by Aleks-MO** [comment] 2020-03-27 06:55
No.

**Comment by tureka** [comment] 2020-04-09 02:47
Why is ESP3D showing a lot less parameters when connected to TFT and so much more when connected straight to board? First screen - to TFT, other three - to SKR1.4T
I was able to configure Marlin both ways. I modified HardwareSerial.h and it worked well.
I am not able to use TFT3.5 when ESP is on board because it's using serial port.
Is it possible to set this up to use THREE ways of connection at once. TFT3.5 v3 - USB - ESP01 to board?
Can anyone help me?
![ESP_TO_SKR14T_1](https://user-images.githubusercontent.com/25722937/78852628-c4541200-7a14-11ea-92a5-bc9d5e5c5b00.jpg)
![ESP_TO_SKR14T_2](https://user-images.githubusercontent.com/25722937/78852629-c4eca880-7a14-11ea-89e1-e33bf7306619.jpg)
![ESP_TO_SKR14T_3](https://user-images.githubusercontent.com/25722937/78852630-c5853f00-7a14-11ea-8064-911ec407488b.jpg)
![ESP_TO_TFT35-v3](https://user-images.githubusercontent.com/25722937/78852632-c5853f00-7a14-11ea-9b08-e6adec732df0.jpg)

**Comment by Interplain** [comment] 2020-04-12 14:46
Is the 1MB model no good, do i have to get the 4MB one. I have found my 1MB one is working with version 1.0, but when i goto the page is shows a web page to upload a firmware. about you dont seem to have a index page. i uploaded the index an it doesnt  do anything else. can someone please help what to do next with the 1mb version.

**Comment by Aardvarx55** [comment] 2020-04-12 15:13
Interplain. Did you manage to get the index file uploaded?
I tried for ages, then realised the FS wasn't big enough to take it...
Not sure if you can get it functioning with 1MB TBH, but hopefully someone will tell you if it's possible...

**Comment by Interplain** [comment] 2020-04-12 17:07
I did upload the index.html.gz file. but it didn't go any further than a please wait page. To be honest this must be a puzzle or some kind cos the instructions are hopeless. I followed the instructions by Chris Riley to the letter and he doesn't have any of this page that we see. Although the instructions are old they should work. if anyone could give some guidance to why this is showing. i have tried the UI in all places to see where its supposed to be saved before compiling.

**Comment by Aardvarx55** [comment] 2020-04-12 17:51
I had the please wait, but the index.html.gz wasn't actually uploading because of lack of space on the FS. What were your board memory settings in Arduino IDE (see attached) ?
And I presume you don't get as far as seeing the web interface-storage page (see attached) ?
![Screen Shot Arduino FFS]

(https://user-images.githubusercontent.com/42945630/79076001-767a2b00-7cee-11ea-90e2-4f223f8e736d.png)

![Screen Shot ESP3D FFS](https://user-images.githubusercontent.com/42945630/79076010-8b56be80-7cee-11ea-9ed5-e5856337667e.png)

**Comment by Interplain** [comment] 2020-04-12 18:20
No, you have done better than me, your total memory is greater than mine by the looks of it. Mine says 1024 and 820kb used. I think it's because there isn't enough memory, an i will have to wait till the ones i have ordered off Ali-express delivered by via Royal Snail..  The 2.1 version compiled in Visual studio and it like made two firmware.elf files. the latter one uploaded, i think there is two bin files for different chip sets. [env:esp32dev] and a [env:esp8266] the latter one uploaded. but didn't log on to the WiFi. this again i think is because of memory limitations.

**Comment by roomme13** [comment] 2020-04-22 11:44
I get the ESP work if i powerit from external source, but if i put it on TFt35 V3.0, it doesnt work anymore.
Any suggestions?  i'm using custom marlin, but with BTT BTT SKR MINI E3 Template

**Comment by roomme13** [comment] 2020-04-22 11:46
> 
> 
> No, you have done better than me, your total memory is greater than mine by the looks of it. Mine says 1024 and 820kb used. I think it's because there isn't enough memory, an i will have to wait till the ones i have ordered off Ali-express delivered by via Royal Snail.. The 2.1 version compiled in Visual studio and it like made two firmware.elf files. the latter one uploaded, i think there is two bin files for different chip sets. [env:esp32dev] and a [env:esp8266] the latter one uploaded. but didn't log on to the WiFi. this again i think is because of memory limitations.
> 
> I used:
> ![Memconfig](https://user-images.githubusercontent.com/32413344/79076563-0d48e680-7cf3-11ea-8015-26a9886ddb06.jpg)

Use FS 128K, and use single language work for me just to run ESP standalone. but still cannot connect it with TFT35

**Comment by redonebe** [comment] 2020-04-22 11:55
@roomme13 

Did you put a 10K resistor between 3,3V and CH_PD ? Otherwise the not original ones don't work on the TFT.

**Comment by roomme13** [comment] 2020-04-22 12:06
> @roomme13 
> 
> Did you put a 10K resistor between 3,3V and CH_PD ? Otherwise the not original ones don't work on the TFT.

Yap it freaking works!!
Thanks!

So if you use "own esp module" , you should do this?

**Comment by redonebe** [comment] 2020-04-22 12:12
I think it depends on the module. On the TFT this pin is not connected. So it is floating.

**Comment by Interplain** [comment] 2020-04-22 12:30
Its the pin output is reversed i believe. so its best to connect to the board with wires an not just plug in. That said, not all boards are the same. the v2.0 is different to the v3.0

**Closed** 2020-08-14 02:38 UTC

**Comment by hmsq82** [comment] 2020-09-14 20:36
> I've got my ESP8266 working now...
> The schematic for the TFT35-E3 V3.0 shows the ch_pd pin as NC (not connected), which I believed would stop the ESP booting, as the ch_pd needs to be high.
> So I connected the it via jumper cables, but connected ch_pd to VCC, and it boots whilst connected to the TFT board... result.
> Having proved that it would boot, I soldered a link directly on the ESP module, and now I can insert it without the jumper cables, and it works.
> I have ESP3D running on it, have it connected to my home network, and am getting responses from the printer... early days for me, as I've never used ESP3D, but my aim is to be able to upload .gcode files via WiFi (I currently print from SD card)
> ![image](https://user-images.githubusercontent.com/42945630/75617075-25edaa80-5b52-11ea-983e-1c32c9d514cd.png)
> ![image](https://user-images.githubusercontent.com/42945630/75617080-36058a00-5b52-11ea-9c63-6a535f6e512e.png)

Thank you so much, spent hours on this until I performed this mod on the ESP01.

**Comment by Talha909** [comment] 2020-12-03 07:52
I have ESP 8266. I successfully installed the software on the ESP. I plug the esp on my lcd. And I connect the esp 8266 from my pc. But when I gave command from the Pc. LCD did not recognized my command.  It gave me lot of error on screen. What should I do for working this.

**Comment by Talha909** [comment] 2020-12-03 07:54
> > I've got my ESP8266 working now...
> > The schematic for the TFT35-E3 V3.0 shows the ch_pd pin as NC (not connected), which I believed would stop the ESP booting, as the ch_pd needs to be high.
> > So I connected the it via jumper cables, but connected ch_pd to VCC, and it boots whilst connected to the TFT board... result.
> > Having proved that it would boot, I soldered a link directly on the ESP module, and now I can insert it without the jumper cables, and it works.
> > I have ESP3D running on it, have it connected to my home network, and am getting responses from the printer... early days for me, as I've never used ESP3D, but my aim is to be able to upload .gcode files via WiFi (I currently print from SD card)
> > ![image](https://user-images.githubusercontent.com/42945630/75617075-25edaa80-5b52-11ea-983e-1c32c9d514cd.png)
> > ![image](https://user-images.githubusercontent.com/42945630/75617080-36058a00-5b52-11ea-9c63-6a535f6e512e.png)
> 
> Thank you so much, spent hours on this until I performed this mod on the ESP01.

Did you make any change in the marlin software for working this.

**Comment by Aardvarx55** [comment] 2020-12-03 11:17
Hi, I'd have to check, but I haven't pursued this further, due to the fact
that I can't upload to the TFT memory devices, and I'm not sure that the
monitoring isn't interfering when printing...
I was hoping someone (more capable) will update ESP3D to allow transfer to
TFT memory.
BTW, I replaced the 'solid' link on the ESP01 with a 10k resistor (on
recommendation).

Good luck, Robbie
